sudo: required
dist: trusty

services:
  - docker

language: cpp

# command to install dependencies
install:
  - mkdir Package
  - mv !(Package) Package
  - export PKGDIR=${PWD}/Package

# command to run tests
script:
  - docker run -it --name CI_container -v $PKGDIR:/home/ilc/Package -d rete/marlinmt-ci
  - docker exec -it CI_container /bin/bash -c "./Package/.travis-ci.d/compile_and_test.sh"

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always
