sudo: required
dist: trusty

services:
  - docker

language: cpp

# command to run tests
script:
  - shopt -s extglob dotglob
  - mkdir Package
  - mv !(Package) Package
  - shopt -u dotglob
  - export PKGDIR=${PWD}/Package
  - docker run -it --name CI_container -v $PKGDIR:/Package -d rete/marlinmt-ci
  - docker exec -it CI_container /bin/bash -c "/Package/.travis-ci.d/compile_and_test.sh"

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always
