MarlinMT: marlinmt::ProcessorApi::Book Class Reference
marlinmt::ProcessorApi::Book Class Reference
group function for booking
#include <ProcessorApi.h>
Static Public Member Functions
static H1FEntry bookHist1F (Processor *proc, const std::filesystem::path &path, const std::string_view &name, const std::string_view &title, const AxisConfigD &axisconfig, const BookFlag_t &flags=BookFlags::Default)
Book a histogram 1D, float type.
static H2FEntry bookHist2F (Processor *proc, const std::filesystem::path &path, const std::string_view &name, const std::string_view &title, const AxisConfigD &axisconfigX, const AxisConfigD &axisconfigY, const BookFlag_t &flags=BookFlags::Default)
Book a histogram 2D, float type.
static H3FEntry bookHist3F (Processor *proc, const std::filesystem::path &path, const std::string_view &name, const std::string_view &title, const AxisConfigD &axisconfigX, const AxisConfigD &axisconfigY, const AxisConfigD &axisconfigZ, const BookFlag_t &flags=BookFlags::Default)
Book a histogram 3D, float type.
static H1DEntry bookHist1D (Processor *proc, const std::filesystem::path &path, const std::string_view &name, const std::string_view &title, const AxisConfigD &axisconfig, const BookFlag_t &flags=BookFlags::Default)
Book a histogram 1D, double type.
static H2DEntry bookHist2D (Processor *proc, const std::filesystem::path &path, const std::string_view &name, const std::string_view &title, const AxisConfigD &axisconfigX, const AxisConfigD &axisconfigY, const BookFlag_t &flags=BookFlags::Default)
Book a histogram 2D, double type.
static H3DEntry bookHist3D (Processor *proc, const std::filesystem::path &path, const std::string_view &name, const std::string_view &title, const AxisConfigD &axisconfigX, const AxisConfigD &axisconfigY, const AxisConfigD &axisconfigZ, const BookFlag_t &flags=BookFlags::Default)
Book a histogram 3D, double type.
static H1IEntry bookHist1I (Processor *proc, const std::filesystem::path &path, const std::string_view &name, const std::string_view &title, const AxisConfigD &axisconfig, const BookFlag_t &flags=BookFlags::Default)
Book a histogram 1D, integer type.
static H2IEntry bookHist2I (Processor *proc, const std::filesystem::path &path, const std::string_view &name, const std::string_view &title, const AxisConfigD &axisconfigX, const AxisConfigD &axisconfigY, const BookFlag_t &flags=BookFlags::Default)
Book a histogram 2D, integer type.
static H3IEntry bookHist3I (Processor *proc, const std::filesystem::path &path, const std::string_view &name, const std::string_view &title, const AxisConfigD &axisconfigX, const AxisConfigD &axisconfigY, const AxisConfigD &axisconfigZ, const BookFlag_t &flags=BookFlags::Default)
Book a histogram 3D, integer type.
static H1FEntry getHist1F (const Processor *proc, const std::filesystem::path &path, const std::string_view &name)
Get handle for booked histogram 1D, float type.
static H2FEntry getHist2F (const Processor *proc, const std::filesystem::path &path, const std::string_view &name)
Get handle for booked histogram 2D, float type.
static H3FEntry getHist3F (const Processor *proc, const std::filesystem::path &path, const std::string_view &name)
Get handle for booked histogram 3D, float type.
static H1DEntry getHist1D (const Processor *proc, const std::filesystem::path &path, const std::string_view &name)
Get handle for booked histogram 1D, double type.
static H2DEntry getHist2D (const Processor *proc, const std::filesystem::path &path, const std::string_view &name)
Get handle for booked histogram 2D, double type.
static H3DEntry getHist3D (const Processor *proc, const std::filesystem::path &path, const std::string_view &name)
Get handle for booked histogram 3D, double type.
static H1IEntry getHist1I (const Processor *proc, const std::filesystem::path &path, const std::string_view &name)
Get handle for booked histogram 1D, integer type.
static H2IEntry getHist2I (const Processor *proc, const std::filesystem::path &path, const std::string_view &name)
Get handle for booked histogram 2D, integer type.
static H3IEntry getHist3I (const Processor *proc, const std::filesystem::path &path, const std::string_view &name)
Get handle for booked histogram 3D, integer type.
static void write (Processor *proc, const std::filesystem::path &path, const std::string_view &name)
register Object to write it at end of lifetime.
static void dontWrite (Processor *proc, const std::filesystem::path &path, const std::string_view &name)
cancels writing of Object at end of lifetime.
static void write (Processor *proc, const book::EntryKey &key)
register Object to write at end of lifetime.
static void dontWrite (Processor *proc, const book::EntryKey &key)
cancels writing of Object at end of lifetime.
Detailed Description
group function for booking
Definition at line 43 of file ProcessorApi.h.
Member Function Documentation
bookHist1D()
H1DEntry marlinmt::ProcessorApi::Book::bookHist1D (Processor * proc, const std::filesystem::path & path, const std::string_view & name, const std::string_view & title, const AxisConfigD & axisconfig, const BookFlag_t & flags = BookFlags::Default) static
Book a histogram 1D, double type.
Parameters
proc the processor booking the histogram
path the histogram entry path
name the histogram name
title the histogram title
axisconfig the histogram X axis config
flags the book flag policy
Definition at line 125 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::BookStoreManager::bookHist(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
bookHist1F()
H1FEntry marlinmt::ProcessorApi::Book::bookHist1F (Processor * proc, const std::filesystem::path & path, const std::string_view & name, const std::string_view & title, const AxisConfigD & axisconfig, const BookFlag_t & flags = BookFlags::Default) static
Book a histogram 1D, float type.
Parameters
proc the processor booking the histogram
path the histogram entry path
name the histogram name
title the histogram title
axisconfig the histogram X axis config
flags the book flag policy
Definition at line 38 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::BookStoreManager::bookHist(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
bookHist1I()
H1IEntry marlinmt::ProcessorApi::Book::bookHist1I (Processor * proc, const std::filesystem::path & path, const std::string_view & name, const std::string_view & title, const AxisConfigD & axisconfig, const BookFlag_t & flags = BookFlags::Default) static
Book a histogram 1D, integer type.
Parameters
proc the processor booking the histogram
path the histogram entry path
name the histogram name
title the histogram title
axisconfig the histogram X axis config
flags the book flag policy
Definition at line 212 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::BookStoreManager::bookHist(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
bookHist2D()
H2DEntry marlinmt::ProcessorApi::Book::bookHist2D (Processor * proc, const std::filesystem::path & path, const std::string_view & name, const std::string_view & title, const AxisConfigD & axisconfigX, const AxisConfigD & axisconfigY, const BookFlag_t & flags = BookFlags::Default) static
Book a histogram 2D, double type.
Parameters
proc the processor booking the histogram
path the histogram entry path
name the histogram name
title the histogram title
axisconfigX the histogram X axis configuration
axisconfigY the histogram Y axis configuration
flags the book flag policy
Definition at line 153 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::BookStoreManager::bookHist(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
bookHist2F()
H2FEntry marlinmt::ProcessorApi::Book::bookHist2F (Processor * proc, const std::filesystem::path & path, const std::string_view & name, const std::string_view & title, const AxisConfigD & axisconfigX, const AxisConfigD & axisconfigY, const BookFlag_t & flags = BookFlags::Default) static
Book a histogram 2D, float type.
Parameters
proc the processor booking the histogram
path the histogram entry path
name the histogram name
title the histogram title
axisconfigX the histogram X axis configuration
axisconfigY the histogram Y axis configuration
flags the book flag policy
Definition at line 66 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::BookStoreManager::bookHist(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
bookHist2I()
H2IEntry marlinmt::ProcessorApi::Book::bookHist2I (Processor * proc, const std::filesystem::path & path, const std::string_view & name, const std::string_view & title, const AxisConfigD & axisconfigX, const AxisConfigD & axisconfigY, const BookFlag_t & flags = BookFlags::Default) static
Book a histogram 2D, integer type.
Parameters
proc the processor booking the histogram
path the histogram entry path
name the histogram name
title the histogram title
axisconfigX the histogram X axis configuration
axisconfigY the histogram Y axis configuration
flags the book flag policy
Definition at line 240 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::BookStoreManager::bookHist(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
bookHist3D()
H3DEntry marlinmt::ProcessorApi::Book::bookHist3D (Processor * proc, const std::filesystem::path & path, const std::string_view & name, const std::string_view & title, const AxisConfigD & axisconfigX, const AxisConfigD & axisconfigY, const AxisConfigD & axisconfigZ, const BookFlag_t & flags = BookFlags::Default) static
Book a histogram 3D, double type.
Parameters
proc the processor booking the histogram
path the histogram entry path
name the histogram name
title the histogram title
axisconfigX the histogram X axis configuration
axisconfigY the histogram Y axis configuration
axisconfigZ the histogram Z axis configuration
flags the book flag policy
Definition at line 182 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::BookStoreManager::bookHist(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
bookHist3F()
H3FEntry marlinmt::ProcessorApi::Book::bookHist3F (Processor * proc, const std::filesystem::path & path, const std::string_view & name, const std::string_view & title, const AxisConfigD & axisconfigX, const AxisConfigD & axisconfigY, const AxisConfigD & axisconfigZ, const BookFlag_t & flags = BookFlags::Default) static
Book a histogram 3D, float type.
Parameters
proc the processor booking the histogram
path the histogram entry path
name the histogram name
title the histogram title
axisconfigX the histogram X axis configuration
axisconfigY the histogram Y axis configuration
axisconfigZ the histogram Z axis configuration
flags the book flag policy
Definition at line 95 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::BookStoreManager::bookHist(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
bookHist3I()
H3IEntry marlinmt::ProcessorApi::Book::bookHist3I (Processor * proc, const std::filesystem::path & path, const std::string_view & name, const std::string_view & title, const AxisConfigD & axisconfigX, const AxisConfigD & axisconfigY, const AxisConfigD & axisconfigZ, const BookFlag_t & flags = BookFlags::Default) static
Book a histogram 3D, integer type.
Parameters
proc the processor booking the histogram
path the histogram entry path
name the histogram name
title the histogram title
axisconfigX the histogram X axis configuration
axisconfigY the histogram Y axis configuration
axisconfigZ the histogram Z axis configuration
flags the book flag policy
Definition at line 269 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::BookStoreManager::bookHist(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
dontWrite() [1/2]
static void marlinmt::ProcessorApi::Book::dontWrite (Processor * proc, const std::filesystem::path & path, const std::string_view & name) static
cancels writing of Object at end of lifetime.
Parameters
proc the processor instance
path to register object
name of object
dontWrite() [2/2]
void marlinmt::ProcessorApi::Book::dontWrite (Processor * proc, const book::EntryKey & key) static
cancels writing of Object at end of lifetime.
Parameters
key of Entry to Object which should be stored.
Definition at line 308 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::Application::bookStoreManager(), and marlinmt::BookStoreManager::removeFromWrite().
getHist1D()
H1DEntry marlinmt::ProcessorApi::Book::getHist1D (const Processor * proc, const std::filesystem::path & path, const std::string_view & name) static
Get handle for booked histogram 1D, double type.
Parameters
proc the processor which booked the histogram
path the histogram entry path
name the histogram name
Definition at line 142 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
getHist1F()
H1FEntry marlinmt::ProcessorApi::Book::getHist1F (const Processor * proc, const std::filesystem::path & path, const std::string_view & name) static
Get handle for booked histogram 1D, float type.
Parameters
proc the processor which booked the histogram
path the histogram entry path
name the histogram name
Definition at line 55 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
getHist1I()
H1IEntry marlinmt::ProcessorApi::Book::getHist1I (const Processor * proc, const std::filesystem::path & path, const std::string_view & name) static
Get handle for booked histogram 1D, integer type.
Parameters
proc the processor which booked the histogram
path the histogram entry path
name the histogram name
Definition at line 229 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
getHist2D()
H2DEntry marlinmt::ProcessorApi::Book::getHist2D (const Processor * proc, const std::filesystem::path & path, const std::string_view & name) static
Get handle for booked histogram 2D, double type.
Parameters
proc the processor which booked the histogram
path the histogram entry path
name the histogram name
Definition at line 171 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
getHist2F()
H2FEntry marlinmt::ProcessorApi::Book::getHist2F (const Processor * proc, const std::filesystem::path & path, const std::string_view & name) static
Get handle for booked histogram 2D, float type.
Parameters
proc the processor which booked the histogram
path the histogram entry path
name the histogram name
Definition at line 84 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
getHist2I()
H2IEntry marlinmt::ProcessorApi::Book::getHist2I (const Processor * proc, const std::filesystem::path & path, const std::string_view & name) static
Get handle for booked histogram 2D, integer type.
Parameters
proc the processor which booked the histogram
path the histogram entry path
name the histogram name
Definition at line 258 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
getHist3D()
H3DEntry marlinmt::ProcessorApi::Book::getHist3D (const Processor * proc, const std::filesystem::path & path, const std::string_view & name) static
Get handle for booked histogram 3D, double type.
Parameters
proc the processor which booked the histogram
path the histogram entry path
name the histogram name
Definition at line 201 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
getHist3F()
H3FEntry marlinmt::ProcessorApi::Book::getHist3F (const Processor * proc, const std::filesystem::path & path, const std::string_view & name) static
Get handle for booked histogram 3D, float type.
Parameters
proc the processor which booked the histogram
path the histogram entry path
name the histogram name
Definition at line 114 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
getHist3I()
H3IEntry marlinmt::ProcessorApi::Book::getHist3I (const Processor * proc, const std::filesystem::path & path, const std::string_view & name) static
Get handle for booked histogram 3D, integer type.
Parameters
proc the processor which booked the histogram
path the histogram entry path
name the histogram name
Definition at line 288 of file ProcessorApi.cc.
References marlinmt::Component::application(), marlinmt::Application::bookStoreManager(), and marlinmt::constructPath().
write() [1/2]
static void marlinmt::ProcessorApi::Book::write (Processor * proc, const std::filesystem::path & path, const std::string_view & name) static
register Object to write it at end of lifetime.
The same effect can archived with passing the Store flag by registration.
Parameters
proc the processor instance
path to registered object
name of object
write() [2/2]
void marlinmt::ProcessorApi::Book::write (Processor * proc, const book::EntryKey & key) static
register Object to write at end of lifetime.
The same effect can archived with passing the Store flag by registration
Parameters
key of Entry to Object which should be stored.
Definition at line 299 of file ProcessorApi.cc.
References marlinmt::BookStoreManager::addToWrite(), marlinmt::Component::application(), and marlinmt::Application::bookStoreManager().
The documentation for this class was generated from the following files:
ProcessorApi.h
ProcessorApi.cc