MarlinMT: marlinmt::clock Class Reference
marlinmt::clock Class Reference
clock class Provide a wrapper around a certain clock type in std to perform safe clock measurement in multi-threading environement
#include <Utils.h>
Public Types
using clock_type = std::chrono::steady_clock
using time_point = clock_type::time_point
using duration_rep = float
using pair = std::pair< duration_rep, duration_rep >
using nanoseconds = std::chrono::duration< duration_rep, std::nano >
using microseconds = std::chrono::duration< duration_rep, std::micro >
using milliseconds = std::chrono::duration< duration_rep, std::milli >
using seconds = std::chrono::duration< duration_rep >
using minutes = std::chrono::duration< duration_rep, std::ratio< 60 > >
Public Member Functions
clock ()=delete
~clock ()=delete
Static Public Member Functions
static time_point now ()
Get the current time.
template<class unit = seconds>
static duration_rep elapsed_since (const time_point &since)
Get the elapsed time since a previous time point.
template<class unit = seconds>
static duration_rep time_difference (const time_point &older, const time_point &ealier)
Get the time difference between two time points.
template<class unit = seconds>
static void crunchFor (duration_rep crunchTime)
Crunch numbers for some time.
Detailed Description
clock class Provide a wrapper around a certain clock type in std to perform safe clock measurement in multi-threading environement
Definition at line 28 of file Utils.h.
Member Typedef Documentation
clock_type
using marlinmt::clock::clock_type = std::chrono::steady_clock
Definition at line 30 of file Utils.h.
duration_rep
using marlinmt::clock::duration_rep = float
Definition at line 32 of file Utils.h.
microseconds
using marlinmt::clock::microseconds = std::chrono::duration<duration_rep, std::micro>
Definition at line 36 of file Utils.h.
milliseconds
using marlinmt::clock::milliseconds = std::chrono::duration<duration_rep, std::milli>
Definition at line 37 of file Utils.h.
minutes
using marlinmt::clock::minutes = std::chrono::duration<duration_rep, std::ratio<60> >
Definition at line 39 of file Utils.h.
nanoseconds
using marlinmt::clock::nanoseconds = std::chrono::duration<duration_rep, std::nano>
Definition at line 35 of file Utils.h.
pair
using marlinmt::clock::pair = std::pair<duration_rep, duration_rep>
Definition at line 33 of file Utils.h.
seconds
using marlinmt::clock::seconds = std::chrono::duration<duration_rep>
Definition at line 38 of file Utils.h.
time_point
using marlinmt::clock::time_point = clock_type::time_point
Definition at line 31 of file Utils.h.
Constructor & Destructor Documentation
clock()
marlinmt::clock::clock () delete
~clock()
marlinmt::clock::~clock () delete
Member Function Documentation
crunchFor()
template<class unit = seconds> static void marlinmt::clock::crunchFor (duration_rep crunchTime) inline static
Crunch numbers for some time.
The template parameter specifies the unit
Parameters
crunchTime the time duration
Definition at line 99 of file Utils.h.
References now().
elapsed_since()
template<class unit = seconds> static duration_rep marlinmt::clock::elapsed_since (const time_point & since) inline static
Get the elapsed time since a previous time point.
The template parameter 'unit' allows for casting the result to a specific unit (default seconds). Use the duration types defined in this class to get a correct calculation. The result is floating type.
Parameters
since an earlier time point
Definition at line 64 of file Utils.h.
References now().
now()
static time_point marlinmt::clock::now () inline static
Get the current time.
Definition at line 50 of file Utils.h.
Referenced by crunchFor(), elapsed_since(), marlinmt::concurrency::PEPScheduler::end(), marlinmt::concurrency::PEPScheduler::initialize(), marlinmt::concurrency::PEPScheduler::popFinishedEvents(), marlinmt::SequenceItem::processEvent(), marlinmt::concurrency::PEPScheduler::processRunHeader(), and marlinmt::concurrency::PEPScheduler::pushEvent().
time_difference()
template<class unit = seconds> static duration_rep marlinmt::clock::time_difference (const time_point & older, const time_point & ealier) inline static
Get the time difference between two time points.
The template parameter 'unit' allows for casting the result to a specific unit (default seconds). Use the duration types defined in this class to get a correct calculation. The result is floating type. Example:
auto start = clock::now();
// do stuff
auto end = clock::now();
// get the time difference in milliseconds as a float
auto ms_spent = clock::time_difference<clock::milliseconds>(start, end);
Parameters
older the oldest time point
ealier the earliest time point
Definition at line 88 of file Utils.h.
Referenced by marlinmt::concurrency::PEPScheduler::end().
The documentation for this class was generated from the following file:
Utils.h