MarlinMT: marlinmt::CPUCrunchingProcessor Class Reference
marlinmt::CPUCrunchingProcessor Class Reference
Simple processor crunching CPU time for n milliseconds.
Inherits marlinmt::Processor.
Public Member Functions
CPUCrunchingProcessor ()
void init () override
Initialize the processor.
void processEvent (EventStore *evt) override
Process an input event.
Public Member Functions inherited from marlinmt::Processor
virtual ~Processor ()=default
Processor (const std::string &t)
Constructor.
virtual void processRunHeader (RunHeader *)
Call at start of run.
virtual void end ()
Terminate the processor.
std::optional< bool > runtimeOption (ERuntimeOption option) const
Get the forced runtime option settings.
Public Member Functions inherited from marlinmt::Component
Component ()=delete
No default constructor.
Component (const Component &)=delete
No copy or assignement.
Component & operator= (const Component &)=delete
virtual ~Component ()=default
Default destructor.
Component (const std::string &type)
Constructor with component type.
const std::string & type () const
Get the component name.
const std::string & name () const
Get the component name.
void setName (const std::string &n)
Set the component name.
const std::string & description () const
Get the component description.
void setDescription (const std::string &desc)
Set the component description.
const Application & application () const
Get the application in which the component is registered.
Application & application ()
Get the application in which the component is registered.
template<class T >
Logging::StreamType log () const
Log a message with specific log level.
Logging::StreamType debug () const
Shortcut for log<DEBUG>()
Logging::StreamType message () const
Shortcut for log<MESSAGE>()
Logging::StreamType warning () const
Shortcut for log<WARNING>()
Logging::StreamType error () const
Shortcut for log<ERROR>()
void setVerbosity (const std::string &level)
Set the verbosity level.
const std::string & verbosity () const
Get the verbosity level.
bool isInitialized () const
Whether the component has been initialized.
void setup (Application *app)
Setup the component.
void printParameters () const
Print the component parameters.
template<class T >
void printParameters () const
Print the component parameters at specific verbosity.
void setParameters (const ConfigSection &section, bool throwIfNotFound=false)
Set the parameters from the configuration section.
void getParameters (ConfigSection &section, const std::set< std::string > &exclude={}) const
Get the parameters from configurable object and populate the config section with.
Public Member Functions inherited from marlinmt::Configurable
Configurable ()=default
virtual ~Configurable ()=default
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value)
Add a parameter.
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value, T defVal)
Add a parameter.
template<typename T >
T parameter (const std::string &name) const
Get a parameter value.
template<typename T >
T parameter (const std::string &name, const T &fallback) const
Get a parameter value.
void checkParameter (const std::string &name) const
Check if the parameter has been registered.
bool exists (const std::string &name) const
Return true if the parameter has been registered.
bool isSet (const std::string &name) const
Returns true if the parameter exists and is set, false otherwise.
void clear ()
Remove all parameters.
void unset ()
Unset all registered parameters.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Private Attributes
IntParameter _crunchTime
FloatParameter _crunchSigma
Additional Inherited Members
Public Types inherited from marlinmt::Processor
enum ERuntimeOption { ERuntimeOption::eCritical, ERuntimeOption::eClone }
ERuntimeOption enumerator.
using RuntimeOptions = std::map< ERuntimeOption, bool >
Public Types inherited from marlinmt::Component
using LoggerPtr = Logging::Logger
Public Types inherited from marlinmt::Configurable
using ParameterMap = std::map< std::string, std::shared_ptr< ParameterImpl > >
using iterator = ParameterMap::iterator
using const_iterator = ParameterMap::const_iterator
Protected Member Functions inherited from marlinmt::Processor
void setRuntimeOption (ERuntimeOption option, bool value)
Force the runtime option to a given boolean value.
Protected Attributes inherited from marlinmt::Component
std::string _type {}
The component type.
std::string _name {}
The component name.
std::string _description {"No description"}
The component description.
Application * _application {nullptr}
The application in which the component has been registered.
LoggerPtr _logger {nullptr}
The logger instance.
StringParameter _verbosity { *this, "Verbosity", "The component verbosity level", "MESSAGE" }
The verbosity level of the logger (parameter)
Protected Attributes inherited from marlinmt::Configurable
ParameterMap _parameters {}
The parameter map.
Detailed Description
Simple processor crunching CPU time for n milliseconds.
Input - Prerequisites
none
Output
none CrunchTime the time in millisecond to crunch CPU
Author
R.Ete, DESY
Definition at line 25 of file CPUCrunchingProcessor.cc.
Constructor & Destructor Documentation
CPUCrunchingProcessor()
marlinmt::CPUCrunchingProcessor::CPUCrunchingProcessor ()
Definition at line 43 of file CPUCrunchingProcessor.cc.
References _crunchSigma, _crunchTime, marlinmt::Component::setDescription(), and marlinmt::ParameterBase< T >::setValidator().
Member Function Documentation
init()
void marlinmt::CPUCrunchingProcessor::init () override virtual
Initialize the processor.
Called at the begin of the job before anything is read. Use to initialize the processor, e.g. book histograms.
Reimplemented from marlinmt::Processor.
Definition at line 54 of file CPUCrunchingProcessor.cc.
References marlinmt::Component::printParameters(), and marlinmt::ProcessorApi::registerForRandomSeeds().
processEvent()
void marlinmt::CPUCrunchingProcessor::processEvent (EventStore *) override virtual
Process an input event.
Called for every event - the working horse.
Reimplemented from marlinmt::Processor.
Definition at line 63 of file CPUCrunchingProcessor.cc.
References _crunchSigma, _crunchTime, marlinmt::ProcessorApi::getRandomSeed(), and MARLINMT_DECLARE_PROCESSOR.
Member Data Documentation
_crunchSigma
FloatParameter marlinmt::CPUCrunchingProcessor::_crunchSigma private
Initial value:
{*this, "CrunchSigma",
             "Smearing factor on the crunching time using a gaussian generator (unit ms)", 0 }
Definition at line 36 of file CPUCrunchingProcessor.cc.
Referenced by CPUCrunchingProcessor(), and processEvent().
_crunchTime
IntParameter marlinmt::CPUCrunchingProcessor::_crunchTime private
Initial value:
{*this, "CrunchTime",
             "The crunching time (unit ms)", 200 }
Definition at line 33 of file CPUCrunchingProcessor.cc.
Referenced by CPUCrunchingProcessor(), and processEvent().
The documentation for this class was generated from the following file:
CPUCrunchingProcessor.cc