MarlinMT: marlinmt::ProcessorConditionsExtension Class Reference
marlinmt::ProcessorConditionsExtension Class Reference
ProcessorConditionsExtension class Event extension providing access to processor runtime conditions (LogicalExpressions)
#include <EventExtensions.h>
Public Types
using Conditions = std::shared_ptr< LogicalExpressions >
using ConditionsMap = std::map< std::string, std::string >
Public Member Functions
~ProcessorConditionsExtension ()=default
ProcessorConditionsExtension ()=delete
ProcessorConditionsExtension (const ProcessorConditionsExtension &)=delete
ProcessorConditionsExtension & operator= (const ProcessorConditionsExtension &)=delete
ProcessorConditionsExtension (const ConditionsMap &conds)
Constructor.
void set (const Processor *const processor, bool value)
Set the runtime condition of the processor.
void set (const Processor *const processor, const std::string &name, bool value)
Set the named runtime condition of the processor.
bool check (const std::string &name) const
Check whether the runtime condition is true.
Private Attributes
Conditions _runtimeConditions {std::make_shared<LogicalExpressions>()}
The runtime conditions.
Detailed Description
ProcessorConditionsExtension class Event extension providing access to processor runtime conditions (LogicalExpressions)
Definition at line 22 of file EventExtensions.h.
Member Typedef Documentation
Conditions
using marlinmt::ProcessorConditionsExtension::Conditions = std::shared_ptr<LogicalExpressions>
Definition at line 24 of file EventExtensions.h.
ConditionsMap
using marlinmt::ProcessorConditionsExtension::ConditionsMap = std::map<std::string, std::string>
Definition at line 25 of file EventExtensions.h.
Constructor & Destructor Documentation
~ProcessorConditionsExtension()
marlinmt::ProcessorConditionsExtension::~ProcessorConditionsExtension () default
ProcessorConditionsExtension() [1/3]
marlinmt::ProcessorConditionsExtension::ProcessorConditionsExtension () delete
ProcessorConditionsExtension() [2/3]
marlinmt::ProcessorConditionsExtension::ProcessorConditionsExtension (const ProcessorConditionsExtension &) delete
ProcessorConditionsExtension() [3/3]
marlinmt::ProcessorConditionsExtension::ProcessorConditionsExtension (const ConditionsMap & conds)
Constructor.
Parameters
conds the initial runtime condition of the event (from steering file)
Definition at line 30 of file EventExtensions.cc.
Member Function Documentation
check()
bool marlinmt::ProcessorConditionsExtension::check (const std::string & name) const
Check whether the runtime condition is true.
Parameters
name the condition name
Definition at line 50 of file EventExtensions.cc.
operator=()
ProcessorConditionsExtension& marlinmt::ProcessorConditionsExtension::operator= (const ProcessorConditionsExtension &) delete
set() [1/2]
void marlinmt::ProcessorConditionsExtension::set (const Processor *const processor, bool value)
Set the runtime condition of the processor.
Parameters
processor the processor pointer
value the runtime condition to set
Definition at line 38 of file EventExtensions.cc.
References marlinmt::Component::name(), and marlinmt::book::Flags::value().
set() [2/2]
void marlinmt::ProcessorConditionsExtension::set (const Processor *const processor, const std::string & name, bool value)
Set the named runtime condition of the processor.
Parameters
processor the processor pointer
name the condition name
value the runtime condition to set
Definition at line 44 of file EventExtensions.cc.
References marlinmt::Component::name(), and marlinmt::book::Flags::value().
Member Data Documentation
_runtimeConditions
Conditions marlinmt::ProcessorConditionsExtension::_runtimeConditions {std::make_shared<LogicalExpressions>()} private
The runtime conditions.
Definition at line 67 of file EventExtensions.h.
The documentation for this class was generated from the following files:
EventExtensions.h
EventExtensions.cc