MarlinMT: marlinmt::Output Class Reference
marlinmt::Output Class Reference
Inherits StdOutput.
Public Member Functions
void failure (TCLAP::CmdLineInterface &c, TCLAP::ArgException &e) override
void usage (TCLAP::CmdLineInterface &c) override
void version (TCLAP::CmdLineInterface &c) override
Detailed Description
Definition at line 15 of file CmdLineParser.cc.
Member Function Documentation
failure()
void marlinmt::Output::failure (TCLAP::CmdLineInterface & c, TCLAP::ArgException & e) inline override
Definition at line 17 of file CmdLineParser.cc.
References MARLINMT_RETHROW, and usage().
usage()
void marlinmt::Output::usage (TCLAP::CmdLineInterface & c) inline override
Definition at line 35 of file CmdLineParser.cc.
References version().
Referenced by failure().
version()
void marlinmt::Output::version (TCLAP::CmdLineInterface & c) inline override
Definition at line 64 of file CmdLineParser.cc.
Referenced by usage().
The documentation for this class was generated from the following file:
CmdLineParser.cc