MarlinMT: marlinmt::book::EntryMultiShared< types::HistT< Config > > Class Template Reference
marlinmt::book::EntryMultiShared< types::HistT< Config > > Class Template Reference
specialisation of EntryMultiShared for Histograms
#include <HistEntry.h>
Inherits marlinmt::book::EntryBase.
Public Types
using Type = types::HistT< Config >
Type of contained Histogram.
using Point_t = typename Type::Point_t
Point type for Hist.
using Weight_t = typename Type::Weight_t
Weight type for Hist.
Public Member Functions
EntryMultiShared (Context context)
constructor
~EntryMultiShared ()
destructor. Flush filler.
EntryMultiShared (const EntryMultiShared &)=default
EntryMultiShared & operator= (const EntryMultiShared &)=default
EntryMultiShared (EntryMultiShared &&)=default
EntryMultiShared & operator= (EntryMultiShared &&)=default
Handle< Type > handle ()
creates a new Handle.
Handle< Type > handle (std::size_t idx)
creates a new Handle with existing buffer.
void flush ()
flush every Buffer from each Handle.
Static Public Attributes
static constexpr Flag_t Flag = EntryMultiShared<void>::Flag
Type Flag. Inherited from default EntrySingle.
Static Private Member Functions
static void fill (const std::shared_ptr< void > &data, Point_t const &x, Weight_t const &w)
add one entry. /ref EntrySingle<types::HistT<Config>>::fill for more information
static void fillN (const std::shared_ptr< void > &data, Point_t const *pFirst, Point_t const *pLast, Weight_t const *wFirst, Weight_t const *wLast)
add N entry. /ref EntrySingle<types::HistT<Config>>::fill for more information
Private Attributes
friend BookStore
Context _context
std::shared_ptr< types::HistConcurrentFillManager< Config > > _fillMgr
Manager to construct Filler.
std::vector< std::weak_ptr< types::HistConcurrentFiller< Config > > > _fillers
list of produced Filler to flush them when needed.
std::vector< std::shared_ptr< types::HistConcurrentFiller< Config > > > _staticFiller {}
list of permanent Filler
std::mutex _fillersExtend {}
lock _fillers when extend memory
Detailed Description
template<typename Config>
class marlinmt::book::EntryMultiShared< types::HistT< Config > >
specialisation of EntryMultiShared for Histograms
Definition at line 205 of file HistEntry.h.
Member Typedef Documentation
Point_t
template<typename Config > using marlinmt::book::EntryMultiShared< types::HistT< Config > >::Point_t = typename Type::Point_t
Point type for Hist.
Definition at line 214 of file HistEntry.h.
Type
template<typename Config > using marlinmt::book::EntryMultiShared< types::HistT< Config > >::Type = types::HistT<Config>
Type of contained Histogram.
Definition at line 212 of file HistEntry.h.
Weight_t
template<typename Config > using marlinmt::book::EntryMultiShared< types::HistT< Config > >::Weight_t = typename Type::Weight_t
Weight type for Hist.
Definition at line 216 of file HistEntry.h.
Constructor & Destructor Documentation
EntryMultiShared() [1/3]
template<typename Config > marlinmt::book::EntryMultiShared< types::HistT< Config > >::EntryMultiShared (Context context) explicit
constructor
~EntryMultiShared()
template<typename Config > marlinmt::book::EntryMultiShared< types::HistT< Config > >::~EntryMultiShared ()
destructor. Flush filler.
Definition at line 254 of file Hist.h.
EntryMultiShared() [2/3]
template<typename Config > marlinmt::book::EntryMultiShared< types::HistT< Config > >::EntryMultiShared (const EntryMultiShared< types::HistT< Config > > &) default
EntryMultiShared() [3/3]
template<typename Config > marlinmt::book::EntryMultiShared< types::HistT< Config > >::EntryMultiShared (EntryMultiShared< types::HistT< Config > > &&) default
Member Function Documentation
fill()
template<typename Config > void marlinmt::book::EntryMultiShared< types::HistT< Config > >::fill (const std::shared_ptr< void > & data, Point_t const & x, Weight_t const & w) inline static private
add one entry. /ref EntrySingle<types::HistT<Config>>::fill for more information
Definition at line 537 of file Hist.h.
fillN()
template<typename Config > void marlinmt::book::EntryMultiShared< types::HistT< Config > >::fillN (const std::shared_ptr< void > & data, Point_t const * pFirst, Point_t const * pLast, Weight_t const * wFirst, Weight_t const * wLast) inline static private
add N entry. /ref EntrySingle<types::HistT<Config>>::fill for more information
Definition at line 548 of file Hist.h.
flush()
template<typename Config > void marlinmt::book::EntryMultiShared< types::HistT< Config > >::flush ()
flush every Buffer from each Handle.
handle() [1/2]
template<typename Config > Handle< types::HistT< Config > > marlinmt::book::EntryMultiShared< types::HistT< Config > >::handle ()
creates a new Handle.
Note
each Handle contains a buffer to reduce synchronisation. This memory will be freed when the handle is destructed.
Definition at line 262 of file Hist.h.
References marlinmt::book::_fillers(), marlinmt::book::_fillMgr, and marlinmt::book::Flags::Book::MultiShared().
handle() [2/2]
template<typename Config > Handle< types::HistT< Config > > marlinmt::book::EntryMultiShared< types::HistT< Config > >::handle (std::size_t idx)
creates a new Handle with existing buffer.
Definition at line 296 of file Hist.h.
References marlinmt::book::_data, marlinmt::book::types::add(), marlinmt::book::BookStore::bookMultiCopy(), marlinmt::book::BookStore::bookMultiShared(), marlinmt::book::BookStore::bookSingle(), marlinmt::book::Flags::Book::MultiCopy(), marlinmt::book::Flags::Book::MultiShared(), marlinmt::book::Flags::Book::Single(), and marlinmt::book::Flags::value().
operator=() [1/2]
template<typename Config > EntryMultiShared& marlinmt::book::EntryMultiShared< types::HistT< Config > >::operator= (const EntryMultiShared< types::HistT< Config > > &) default
operator=() [2/2]
template<typename Config > EntryMultiShared& marlinmt::book::EntryMultiShared< types::HistT< Config > >::operator= (EntryMultiShared< types::HistT< Config > > &&) default
Member Data Documentation
_context
template<typename Config > Context marlinmt::book::EntryMultiShared< types::HistT< Config > >::_context private
See also
{EntrySingle::_context}
Definition at line 262 of file HistEntry.h.
_fillers
template<typename Config > std::vector< std::weak_ptr< types::HistConcurrentFiller< Config > > > marlinmt::book::EntryMultiShared< types::HistT< Config > >::_fillers private
list of produced Filler to flush them when needed.
Definition at line 267 of file HistEntry.h.
_fillersExtend
template<typename Config > std::mutex marlinmt::book::EntryMultiShared< types::HistT< Config > >::_fillersExtend {} private
lock _fillers when extend memory
Definition at line 272 of file HistEntry.h.
_fillMgr
template<typename Config > std::shared_ptr< types::HistConcurrentFillManager< Config > > marlinmt::book::EntryMultiShared< types::HistT< Config > >::_fillMgr private
Manager to construct Filler.
Definition at line 264 of file HistEntry.h.
_staticFiller
template<typename Config > std::vector< std::shared_ptr<types::HistConcurrentFiller< Config > > > marlinmt::book::EntryMultiShared< types::HistT< Config > >::_staticFiller {} private
list of permanent Filler
Definition at line 270 of file HistEntry.h.
BookStore
template<typename Config > friend marlinmt::book::EntryMultiShared< types::HistT< Config > >::BookStore private
Definition at line 207 of file HistEntry.h.
Flag
template<typename Config > constexpr Flag_t marlinmt::book::EntryMultiShared< types::HistT< Config > >::Flag = EntryMultiShared<void>::Flag static
Type Flag. Inherited from default EntrySingle.
Definition at line 219 of file HistEntry.h.
The documentation for this class was generated from the following files:
HistEntry.h
Hist.h