MarlinMT: marlinmt::book::types::AxisConfig< Precision_t > Class Template Reference
marlinmt::book::types::AxisConfig< Precision_t > Class Template Reference
collection for Axis Description
#include <Base.h>
Public Member Functions
AxisConfig (const std::string_view &title, std::size_t bins, Precision_t min, Precision_t max)
Axis with equal sized bins.
AxisConfig (std::size_t bins, Precision_t min, Precision_t max)
Axis with equal sized bins.
template<typename Itr >
AxisConfig (const std::string_view &title, Itr begin, Itr end)
Axis with irregular borders.
template<typename Itr >
AxisConfig (Itr begin, Itr end)
Axis with irregular borders.
template<typename Container >
AxisConfig (const std::string_view &title, const Container &container)
Axis with irregular borders.
std::string_view title () const
Get Axis Title.
std::size_t bins () const
Get amount of bins.
Precision_t min () const
Get lower bound.
Precision_t max () const
Get upper bound.
bool isRegular () const
check if bins are equal sized.
const std::vector< Precision_t > & iregularBorder () const
get borders, when borders are irregular.
Private Attributes
std::string _title
std::size_t _bins
Precision_t _min
Precision_t _max
std::optional< std::vector< Precision_t > > _iregularBorder {std::nullopt}
Detailed Description
template<typename Precision_t>
class marlinmt::book::types::AxisConfig< Precision_t >
collection for Axis Description
Definition at line 23 of file Base.h.
Constructor & Destructor Documentation
AxisConfig() [1/5]
template<typename Precision_t> marlinmt::book::types::AxisConfig< Precision_t >::AxisConfig (const std::string_view & title, std::size_t bins, Precision_t min, Precision_t max) inline
Axis with equal sized bins.
Parameters
title of the axis
bins amount of bins
min lower limit
max upper limit
Definition at line 33 of file Base.h.
References marlinmt::book::types::AxisConfig< Precision_t >::_max, marlinmt::book::types::AxisConfig< Precision_t >::_min, marlinmt::book::types::AxisConfig< Precision_t >::max(), and marlinmt::book::types::AxisConfig< Precision_t >::min().
AxisConfig() [2/5]
template<typename Precision_t> marlinmt::book::types::AxisConfig< Precision_t >::AxisConfig (std::size_t bins, Precision_t min, Precision_t max) inline
Axis with equal sized bins.
Parameters
bins number of bins
min lower limit
max upper limit
Definition at line 46 of file Base.h.
AxisConfig() [3/5]
template<typename Precision_t> template<typename Itr > marlinmt::book::types::AxisConfig< Precision_t >::AxisConfig (const std::string_view & title, Itr begin, Itr end) inline
Axis with irregular borders.
Parameters
title title
Template Parameters
Itr iterator type
Parameters
begin,end range to copy bins
begin … lower bound
end - 1 … upper bound
(begin - end) - 1 … amount of bins
Definition at line 61 of file Base.h.
References marlinmt::book::types::AxisConfig< Precision_t >::_iregularBorder, marlinmt::book::types::AxisConfig< Precision_t >::_max, and marlinmt::book::types::AxisConfig< Precision_t >::_min.
AxisConfig() [4/5]
template<typename Precision_t> template<typename Itr > marlinmt::book::types::AxisConfig< Precision_t >::AxisConfig (Itr begin, Itr end) inline explicit
Axis with irregular borders.
Template Parameters
Itr iterator type
Parameters
begin,end range to copy bins
begin … lower bound
end - 1 … upper bound
(begin - end) - 1 … amount of bins
Definition at line 80 of file Base.h.
AxisConfig() [5/5]
template<typename Precision_t> template<typename Container > marlinmt::book::types::AxisConfig< Precision_t >::AxisConfig (const std::string_view & title, const Container & container) inline
Axis with irregular borders.
Template Parameters
Container type of Container which includes bin border. (need begin, end)
Parameters
title title
container with bin borders
Definition at line 90 of file Base.h.
Member Function Documentation
bins()
template<typename Precision_t> std::size_t marlinmt::book::types::AxisConfig< Precision_t >::bins () const inline
Get amount of bins.
Definition at line 101 of file Base.h.
References marlinmt::book::types::AxisConfig< Precision_t >::_bins.
iregularBorder()
template<typename Precision_t> const std::vector<Precision_t>& marlinmt::book::types::AxisConfig< Precision_t >::iregularBorder () const inline
get borders, when borders are irregular.
Returns
vector of irregular borers, or empty vector if bins equal sized.
Definition at line 119 of file Base.h.
References marlinmt::book::types::AxisConfig< Precision_t >::_iregularBorder.
isRegular()
template<typename Precision_t> bool marlinmt::book::types::AxisConfig< Precision_t >::isRegular () const inline
check if bins are equal sized.
Definition at line 113 of file Base.h.
References marlinmt::book::types::AxisConfig< Precision_t >::_iregularBorder.
max()
template<typename Precision_t> Precision_t marlinmt::book::types::AxisConfig< Precision_t >::max () const inline
Get upper bound.
Definition at line 109 of file Base.h.
References marlinmt::book::types::AxisConfig< Precision_t >::_max.
Referenced by marlinmt::book::types::AxisConfig< Precision_t >::AxisConfig().
min()
template<typename Precision_t> Precision_t marlinmt::book::types::AxisConfig< Precision_t >::min () const inline
Get lower bound.
Definition at line 105 of file Base.h.
References marlinmt::book::types::AxisConfig< Precision_t >::_min.
Referenced by marlinmt::book::types::AxisConfig< Precision_t >::AxisConfig().
title()
template<typename Precision_t> std::string_view marlinmt::book::types::AxisConfig< Precision_t >::title () const inline
Get Axis Title.
Definition at line 97 of file Base.h.
References marlinmt::book::types::AxisConfig< Precision_t >::_title.
Referenced by marlinmt::book::types::HistT< Config >::HistT().
Member Data Documentation
_bins
template<typename Precision_t> std::size_t marlinmt::book::types::AxisConfig< Precision_t >::_bins private
Definition at line 124 of file Base.h.
Referenced by marlinmt::book::types::AxisConfig< Precision_t >::bins().
_iregularBorder
template<typename Precision_t> std::optional<std::vector<Precision_t> > marlinmt::book::types::AxisConfig< Precision_t >::_iregularBorder {std::nullopt} private
Definition at line 127 of file Base.h.
Referenced by marlinmt::book::types::AxisConfig< Precision_t >::AxisConfig(), marlinmt::book::types::AxisConfig< Precision_t >::iregularBorder(), and marlinmt::book::types::AxisConfig< Precision_t >::isRegular().
_max
template<typename Precision_t> Precision_t marlinmt::book::types::AxisConfig< Precision_t >::_max private
Definition at line 126 of file Base.h.
Referenced by marlinmt::book::types::AxisConfig< Precision_t >::AxisConfig(), and marlinmt::book::types::AxisConfig< Precision_t >::max().
_min
template<typename Precision_t> Precision_t marlinmt::book::types::AxisConfig< Precision_t >::_min private
Definition at line 125 of file Base.h.
Referenced by marlinmt::book::types::AxisConfig< Precision_t >::AxisConfig(), and marlinmt::book::types::AxisConfig< Precision_t >::min().
_title
template<typename Precision_t> std::string marlinmt::book::types::AxisConfig< Precision_t >::_title private
Definition at line 123 of file Base.h.
Referenced by marlinmt::book::types::AxisConfig< Precision_t >::title().
The documentation for this class was generated from the following file:
Base.h