MarlinMT: marlinmt::book::MemLayout Class Reference
marlinmt::book::MemLayout Class Reference abstract
MemLayout base class to store booked objects in MarlinMT.
#include <MemLayout.h>
Inherited by marlinmt::book::SharedMemLayout< T, MERGE, Args_t >, and marlinmt::book::SingleMemLayout< T, Args_t >.
Public Member Functions
template<typename T >
std::shared_ptr< const T > at (std::size_t idx) const
Get Resource for an instance.
template<typename T >
std::shared_ptr< T > at (std::size_t idx)
Get Resource for an instance.
template<typename T >
std::shared_ptr< const T > merged ()
Get Completed Resource.
MemLayout ()=default
MemLayout (const MemLayout &)=default
MemLayout & operator= (const MemLayout &)=default
MemLayout (MemLayout &&)=default
MemLayout & operator= (MemLayout &&)=default
virtual ~MemLayout ()=default
Protected Member Functions
virtual std::shared_ptr< void > impAt (std::size_t idx) const =0
implementation from at
virtual std::shared_ptr< void > impMerged ()=0
implementation from merged
Detailed Description
MemLayout base class to store booked objects in MarlinMT.
Definition at line 14 of file MemLayout.h.
Constructor & Destructor Documentation
MemLayout() [1/3]
marlinmt::book::MemLayout::MemLayout () default
Referenced by merged().
MemLayout() [2/3]
marlinmt::book::MemLayout::MemLayout (const MemLayout &) default
MemLayout() [3/3]
marlinmt::book::MemLayout::MemLayout (MemLayout &&) default
~MemLayout()
virtual marlinmt::book::MemLayout::~MemLayout () virtual default
Referenced by merged().
Member Function Documentation
at() [1/2]
template<typename T > std::shared_ptr< const T > marlinmt::book::MemLayout::at (std::size_t idx) const inline
Get Resource for an instance.
Parameters
idx instance id
Returns
const pointer to Resource
Definition at line 22 of file MemLayout.h.
References impAt().
at() [2/2]
template<typename T > std::shared_ptr< T > marlinmt::book::MemLayout::at (std::size_t idx) inline
Get Resource for an instance.
Parameters
idx instance id
Returns
pointer to Resource
Definition at line 32 of file MemLayout.h.
References impAt().
impAt()
virtual std::shared_ptr< void > marlinmt::book::MemLayout::impAt (std::size_t idx) const protected pure virtual
implementation from at
Implemented in marlinmt::book::SingleMemLayout< T, Args_t >, and marlinmt::book::SharedMemLayout< T, MERGE, Args_t >.
Referenced by at(), and merged().
impMerged()
virtual std::shared_ptr< void > marlinmt::book::MemLayout::impMerged () protected pure virtual
implementation from merged
Implemented in marlinmt::book::SingleMemLayout< T, Args_t >, and marlinmt::book::SharedMemLayout< T, MERGE, Args_t >.
Referenced by merged().
merged()
template<typename T > std::shared_ptr< const T > marlinmt::book::MemLayout::merged () inline
Get Completed Resource.
Same for every Instance.
Note
may recalculation for every call
Definition at line 41 of file MemLayout.h.
References impAt(), impMerged(), MemLayout(), operator=(), and ~MemLayout().
operator=() [1/2]
MemLayout& marlinmt::book::MemLayout::operator= (const MemLayout &) default
Referenced by merged(), marlinmt::book::SharedMemLayout< T, MERGE, Args_t >::SharedMemLayout(), and marlinmt::book::SingleMemLayout< T, Args_t >::SingleMemLayout().
operator=() [2/2]
MemLayout& marlinmt::book::MemLayout::operator= (MemLayout &&) default
The documentation for this class was generated from the following file:
MemLayout.h