MarlinMT: marlinmt::DataSourcePlugin Class Reference
marlinmt::DataSourcePlugin Class Reference abstract
DataSourcePlugin class Responsible for reading/getting LCEvent and LCRunHeader in the framework for further processing.
#include <DataSourcePlugin.h>
Inherits marlinmt::Component.
Inherited by marlinmt::LCIOFileSource, and marlinmt::StdHepFileSource.
Public Types
using EventFunction = std::function< void(std::shared_ptr< EventStore >)>
using RunHeaderFunction = std::function< void(std::shared_ptr< RunHeader >)>
Public Types inherited from marlinmt::Component
using LoggerPtr = Logging::Logger
Public Types inherited from marlinmt::Configurable
using ParameterMap = std::map< std::string, std::shared_ptr< ParameterImpl > >
using iterator = ParameterMap::iterator
using const_iterator = ParameterMap::const_iterator
Public Member Functions
virtual ~DataSourcePlugin ()=default
DataSourcePlugin (const std::string &dstype)
Constructor.
const std::string & type () const
Get the data source type.
const std::string & description () const
Get the data source description.
virtual bool readOne ()=0
Read one record from the input stream.
virtual void readAll ()
Read the full stream until the end See readOne() for details.
void onEventRead (EventFunction func)
Set the callback function to process on event read.
void onRunHeaderRead (RunHeaderFunction func)
Set the callback function to process on run header read.
Public Member Functions inherited from marlinmt::Component
Component ()=delete
No default constructor.
Component (const Component &)=delete
No copy or assignement.
Component & operator= (const Component &)=delete
virtual ~Component ()=default
Default destructor.
Component (const std::string &type)
Constructor with component type.
const std::string & type () const
Get the component name.
const std::string & name () const
Get the component name.
void setName (const std::string &n)
Set the component name.
const std::string & description () const
Get the component description.
void setDescription (const std::string &desc)
Set the component description.
const Application & application () const
Get the application in which the component is registered.
Application & application ()
Get the application in which the component is registered.
template<class T >
Logging::StreamType log () const
Log a message with specific log level.
Logging::StreamType debug () const
Shortcut for log<DEBUG>()
Logging::StreamType message () const
Shortcut for log<MESSAGE>()
Logging::StreamType warning () const
Shortcut for log<WARNING>()
Logging::StreamType error () const
Shortcut for log<ERROR>()
void setVerbosity (const std::string &level)
Set the verbosity level.
const std::string & verbosity () const
Get the verbosity level.
bool isInitialized () const
Whether the component has been initialized.
void setup (Application *app)
Setup the component.
void printParameters () const
Print the component parameters.
template<class T >
void printParameters () const
Print the component parameters at specific verbosity.
void setParameters (const ConfigSection &section, bool throwIfNotFound=false)
Set the parameters from the configuration section.
void getParameters (ConfigSection &section, const std::set< std::string > &exclude={}) const
Get the parameters from configurable object and populate the config section with.
Public Member Functions inherited from marlinmt::Configurable
Configurable ()=default
virtual ~Configurable ()=default
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value)
Add a parameter.
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value, T defVal)
Add a parameter.
template<typename T >
T parameter (const std::string &name) const
Get a parameter value.
template<typename T >
T parameter (const std::string &name, const T &fallback) const
Get a parameter value.
void checkParameter (const std::string &name) const
Check if the parameter has been registered.
bool exists (const std::string &name) const
Return true if the parameter has been registered.
bool isSet (const std::string &name) const
Returns true if the parameter exists and is set, false otherwise.
void clear ()
Remove all parameters.
void unset ()
Unset all registered parameters.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Protected Member Functions
void processRunHeader (std::shared_ptr< RunHeader > rhdr)
Must be called by daughter classes in readStream() to process an event in the framework.
void processEvent (std::shared_ptr< EventStore > event)
Must be called by daughter classes in readStream() to process an event in the framework.
virtual void initialize () override
Init data source.
Protected Attributes
std::string _description {"No description"}
< The data source description
Protected Attributes inherited from marlinmt::Component
std::string _type {}
The component type.
std::string _name {}
The component name.
std::string _description {"No description"}
The component description.
Application * _application {nullptr}
The application in which the component has been registered.
LoggerPtr _logger {nullptr}
The logger instance.
StringParameter _verbosity { *this, "Verbosity", "The component verbosity level", "MESSAGE" }
The verbosity level of the logger (parameter)
Protected Attributes inherited from marlinmt::Configurable
ParameterMap _parameters {}
The parameter map.
Private Attributes
EventFunction _onEventRead {nullptr}
< The callback function on event read
RunHeaderFunction _onRunHeaderRead {nullptr}
Detailed Description
DataSourcePlugin class Responsible for reading/getting LCEvent and LCRunHeader in the framework for further processing.
Definition at line 24 of file DataSourcePlugin.h.
Member Typedef Documentation
EventFunction
using marlinmt::DataSourcePlugin::EventFunction = std::function<void(std::shared_ptr<EventStore>)>
Definition at line 26 of file DataSourcePlugin.h.
RunHeaderFunction
using marlinmt::DataSourcePlugin::RunHeaderFunction = std::function<void(std::shared_ptr<RunHeader>)>
Definition at line 27 of file DataSourcePlugin.h.
Constructor & Destructor Documentation
~DataSourcePlugin()
virtual marlinmt::DataSourcePlugin::~DataSourcePlugin () virtual default
DataSourcePlugin()
marlinmt::DataSourcePlugin::DataSourcePlugin (const std::string & dstype)
Constructor.
Parameters
dstype the data source plugin type
Definition at line 10 of file DataSourcePlugin.cc.
Member Function Documentation
description()
const std::string& marlinmt::DataSourcePlugin::description () const
Get the data source description.
initialize()
void marlinmt::DataSourcePlugin::initialize () override protected virtual
Init data source.
Reimplemented from marlinmt::Component.
Reimplemented in marlinmt::LCIOFileSource, and marlinmt::StdHepFileSource.
Definition at line 53 of file DataSourcePlugin.cc.
References marlinmt::Component::application(), marlinmt::Application::configuration(), and marlinmt::Component::setParameters().
Referenced by marlinmt::StdHepFileSource::initialize(), and marlinmt::LCIOFileSource::initialize().
onEventRead()
void marlinmt::DataSourcePlugin::onEventRead (EventFunction func)
Set the callback function to process on event read.
Parameters
func the callback function
Definition at line 23 of file DataSourcePlugin.cc.
References _onEventRead.
onRunHeaderRead()
void marlinmt::DataSourcePlugin::onRunHeaderRead (RunHeaderFunction func)
Set the callback function to process on run header read.
Parameters
func the callback function
Definition at line 29 of file DataSourcePlugin.cc.
References _onRunHeaderRead.
processEvent()
void marlinmt::DataSourcePlugin::processEvent (std::shared_ptr< EventStore > event) protected
Must be called by daughter classes in readStream() to process an event in the framework.
Parameters
event the event to process
Definition at line 44 of file DataSourcePlugin.cc.
References _onEventRead.
Referenced by marlinmt::LCIOFileSource::initialize(), and marlinmt::StdHepFileSource::readOne().
processRunHeader()
void marlinmt::DataSourcePlugin::processRunHeader (std::shared_ptr< RunHeader > rhdr) protected
Must be called by daughter classes in readStream() to process an event in the framework.
Parameters
event the event to process
Definition at line 35 of file DataSourcePlugin.cc.
References _onRunHeaderRead.
Referenced by marlinmt::LCIOFileSource::initialize(), and marlinmt::StdHepFileSource::readOne().
readAll()
void marlinmt::DataSourcePlugin::readAll () virtual
Read the full stream until the end See readOne() for details.
Definition at line 17 of file DataSourcePlugin.cc.
References readOne().
readOne()
virtual bool marlinmt::DataSourcePlugin::readOne () pure virtual
Read one record from the input stream.
Users must call processRunHeader() or processEvent() to forward it to the framework. Returns true on success. If the end of the stream is reached, return false.
Implemented in marlinmt::LCIOFileSource, and marlinmt::StdHepFileSource.
Referenced by readAll().
type()
const std::string& marlinmt::DataSourcePlugin::type () const
Get the data source type.
Member Data Documentation
_description
std::string marlinmt::DataSourcePlugin::_description {"No description"} protected
< The data source description
Definition at line 100 of file DataSourcePlugin.h.
_onEventRead
EventFunction marlinmt::DataSourcePlugin::_onEventRead {nullptr} private
< The callback function on event read
The callback function on run header read
Definition at line 104 of file DataSourcePlugin.h.
Referenced by onEventRead(), and processEvent().
_onRunHeaderRead
RunHeaderFunction marlinmt::DataSourcePlugin::_onRunHeaderRead {nullptr} private
Definition at line 106 of file DataSourcePlugin.h.
Referenced by onRunHeaderRead(), and processRunHeader().
The documentation for this class was generated from the following files:
DataSourcePlugin.h
DataSourcePlugin.cc