MarlinMT: marlinmt::concurrency::Queue< T, class > Class Template Reference
marlinmt::concurrency::Queue< T, class > Class Template Reference
Queue class.
#include <Queue.h>
Public Member Functions
Queue ()=default
~Queue ()=default
Queue (const Queue &)=delete
Queue & operator= (const Queue &)=delete
Queue (std::size_t maxsize)
Constructor.
bool push (T &value)
Push a value to the queue.
bool pop (T &value)
Pop and get the front element in the queue.
bool empty () const
Whether the queue is empty.
std::size_t maxSize () const
Get the maximum queue size.
std::size_t setMaxSize (std::size_t maxsize)
Set the maximum queue size.
bool isFull () const
Check whether the queue has reached the maximum allowed size.
void clear ()
Clear the queue.
std::size_t freeSlots () const
Get the number of free slots in the queue.
Private Attributes
std::queue< T > _queue {}
The underlying queue object.
std::mutex _mutex {}
The synchronization mutex.
std::size_t _maxSize {std::numeric_limits<std::size_t>::max()}
The maximum size of the queue.
Detailed Description
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type>
class marlinmt::concurrency::Queue< T, class >
Queue class.
A simplified thread safe queue container. Support maximum size setting. The type T must implement move assignement
Definition at line 22 of file Queue.h.
Constructor & Destructor Documentation
Queue() [1/3]
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> marlinmt::concurrency::Queue< T, class >::Queue () default
~Queue()
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> marlinmt::concurrency::Queue< T, class >::~Queue () default
Queue() [2/3]
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> marlinmt::concurrency::Queue< T, class >::Queue (const Queue< T, class > &) delete
Queue() [3/3]
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> marlinmt::concurrency::Queue< T, class >::Queue (std::size_t maxsize) inline
Constructor.
Parameters
maxsize the maximum queue size
Definition at line 34 of file Queue.h.
Member Function Documentation
clear()
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> void marlinmt::concurrency::Queue< T, class >::clear () inline
Clear the queue.
Definition at line 110 of file Queue.h.
Referenced by marlinmt::concurrency::ThreadPool< InputType, OutputType >::clearQueue(), and marlinmt::concurrency::ThreadPool< InputType, OutputType >::stop().
empty()
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> bool marlinmt::concurrency::Queue< T, class >::empty () const inline
Whether the queue is empty.
Definition at line 73 of file Queue.h.
Referenced by marlinmt::concurrency::ThreadPool< InputType, OutputType >::active(), and marlinmt::concurrency::ThreadPool< InputType, OutputType >::isQueueEmpty().
freeSlots()
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> std::size_t marlinmt::concurrency::Queue< T, class >::freeSlots () const inline
Get the number of free slots in the queue.
Definition at line 120 of file Queue.h.
Referenced by marlinmt::concurrency::ThreadPool< InputType, OutputType >::freeSlots().
isFull()
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> bool marlinmt::concurrency::Queue< T, class >::isFull () const inline
Check whether the queue has reached the maximum allowed size.
Definition at line 102 of file Queue.h.
Referenced by marlinmt::concurrency::ThreadPool< InputType, OutputType >::push().
maxSize()
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> std::size_t marlinmt::concurrency::Queue< T, class >::maxSize () const inline
Get the maximum queue size.
Definition at line 81 of file Queue.h.
operator=()
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> Queue& marlinmt::concurrency::Queue< T, class >::operator= (const Queue< T, class > &) delete
pop()
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> bool marlinmt::concurrency::Queue< T, class >::pop (T & value) inline
Pop and get the front element in the queue.
The queue type must support move operation
Parameters
value the value to receive
Definition at line 60 of file Queue.h.
Referenced by marlinmt::concurrency::Worker< IN, OUT >::run().
push()
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> bool marlinmt::concurrency::Queue< T, class >::push (T & value) inline
Push a value to the queue.
WARNING: On success, the element is moved in the queue container, else it is not !
Parameters
value the value to push
Definition at line 45 of file Queue.h.
Referenced by marlinmt::concurrency::ThreadPool< InputType, OutputType >::push().
setMaxSize()
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> std::size_t marlinmt::concurrency::Queue< T, class >::setMaxSize (std::size_t maxsize) inline
Set the maximum queue size.
Note that the queue is NOT resized if the new value is smaller than the old size. The value of the old max size is returned
Parameters
maxsize the maximum queue size to set
Definition at line 93 of file Queue.h.
Referenced by marlinmt::concurrency::ThreadPool< InputType, OutputType >::setMaxQueueSize().
Member Data Documentation
_maxSize
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> std::size_t marlinmt::concurrency::Queue< T, class >::_maxSize {std::numeric_limits<std::size_t>::max()} private
The maximum size of the queue.
Definition at line 131 of file Queue.h.
Referenced by marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::freeSlots(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::isFull(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::maxSize(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::push(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::Queue(), and marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::setMaxSize().
_mutex
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> std::mutex marlinmt::concurrency::Queue< T, class >::_mutex {} mutable private
The synchronization mutex.
Definition at line 129 of file Queue.h.
Referenced by marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::clear(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::empty(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::freeSlots(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::isFull(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::maxSize(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::pop(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::push(), and marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::setMaxSize().
_queue
template<typename T, class = typename std::enable_if<std::is_move_assignable<T>::value>::type> std::queue<T> marlinmt::concurrency::Queue< T, class >::_queue {} private
The underlying queue object.
Definition at line 127 of file Queue.h.
Referenced by marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::clear(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::empty(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::freeSlots(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::isFull(), marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::pop(), and marlinmt::concurrency::Queue< QueueElement< InputType, OutputType > >::push().
The documentation for this class was generated from the following file:
Queue.h