MarlinMT: marlinmt::IScheduler Class Reference
marlinmt::IScheduler Class Reference abstract
IScheduler interface Interface for implementing a scheduling algorithm for event processing.
#include <IScheduler.h>
Inherits marlinmt::Component.
Inherited by marlinmt::concurrency::PEPScheduler, and marlinmt::SimpleScheduler.
Public Member Functions
IScheduler ()
Constructor.
virtual ~IScheduler ()=default
virtual void initialize () override
Initialize the scheduler.
virtual void end ()=0
Terminate the scheduler activites Cleanup memory, etc ...
virtual void processRunHeader (std::shared_ptr< RunHeader > rhdr)=0
Process a run header.
virtual void pushEvent (std::shared_ptr< EventStore > event)=0
Push a new event to the scheduler for processing.
virtual void popFinishedEvents (std::vector< std::shared_ptr< EventStore >> &events)=0
Retrieve finished events from the scheduler.
virtual std::size_t freeSlots () const =0
Get the number of free event slots.
Public Member Functions inherited from marlinmt::Component
Component ()=delete
No default constructor.
Component (const Component &)=delete
No copy or assignement.
Component & operator= (const Component &)=delete
virtual ~Component ()=default
Default destructor.
Component (const std::string &type)
Constructor with component type.
const std::string & type () const
Get the component name.
const std::string & name () const
Get the component name.
void setName (const std::string &n)
Set the component name.
const std::string & description () const
Get the component description.
void setDescription (const std::string &desc)
Set the component description.
const Application & application () const
Get the application in which the component is registered.
Application & application ()
Get the application in which the component is registered.
template<class T >
Logging::StreamType log () const
Log a message with specific log level.
Logging::StreamType debug () const
Shortcut for log<DEBUG>()
Logging::StreamType message () const
Shortcut for log<MESSAGE>()
Logging::StreamType warning () const
Shortcut for log<WARNING>()
Logging::StreamType error () const
Shortcut for log<ERROR>()
void setVerbosity (const std::string &level)
Set the verbosity level.
const std::string & verbosity () const
Get the verbosity level.
bool isInitialized () const
Whether the component has been initialized.
void setup (Application *app)
Setup the component.
void printParameters () const
Print the component parameters.
template<class T >
void printParameters () const
Print the component parameters at specific verbosity.
void setParameters (const ConfigSection &section, bool throwIfNotFound=false)
Set the parameters from the configuration section.
void getParameters (ConfigSection &section, const std::set< std::string > &exclude={}) const
Get the parameters from configurable object and populate the config section with.
Public Member Functions inherited from marlinmt::Configurable
Configurable ()=default
virtual ~Configurable ()=default
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value)
Add a parameter.
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value, T defVal)
Add a parameter.
template<typename T >
T parameter (const std::string &name) const
Get a parameter value.
template<typename T >
T parameter (const std::string &name, const T &fallback) const
Get a parameter value.
void checkParameter (const std::string &name) const
Check if the parameter has been registered.
bool exists (const std::string &name) const
Return true if the parameter has been registered.
bool isSet (const std::string &name) const
Returns true if the parameter exists and is set, false otherwise.
void clear ()
Remove all parameters.
void unset ()
Unset all registered parameters.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Additional Inherited Members
Public Types inherited from marlinmt::Component
using LoggerPtr = Logging::Logger
Public Types inherited from marlinmt::Configurable
using ParameterMap = std::map< std::string, std::shared_ptr< ParameterImpl > >
using iterator = ParameterMap::iterator
using const_iterator = ParameterMap::const_iterator
Protected Attributes inherited from marlinmt::Component
std::string _type {}
The component type.
std::string _name {}
The component name.
std::string _description {"No description"}
The component description.
Application * _application {nullptr}
The application in which the component has been registered.
LoggerPtr _logger {nullptr}
The logger instance.
StringParameter _verbosity { *this, "Verbosity", "The component verbosity level", "MESSAGE" }
The verbosity level of the logger (parameter)
Protected Attributes inherited from marlinmt::Configurable
ParameterMap _parameters {}
The parameter map.
Detailed Description
IScheduler interface Interface for implementing a scheduling algorithm for event processing.
The scheduling can be sequential or parallel (inter-event / intra-event / both). See implementation classes for more details.
Definition at line 23 of file IScheduler.h.
Constructor & Destructor Documentation
IScheduler()
marlinmt::IScheduler::IScheduler ()
Constructor.
Definition at line 8 of file IScheduler.cc.
~IScheduler()
virtual marlinmt::IScheduler::~IScheduler () virtual default
Member Function Documentation
end()
virtual void marlinmt::IScheduler::end () pure virtual
Terminate the scheduler activites Cleanup memory, etc ...
Implemented in marlinmt::concurrency::PEPScheduler, and marlinmt::SimpleScheduler.
freeSlots()
virtual std::size_t marlinmt::IScheduler::freeSlots () const pure virtual
Get the number of free event slots.
Implemented in marlinmt::concurrency::PEPScheduler, and marlinmt::SimpleScheduler.
initialize()
void marlinmt::IScheduler::initialize () override virtual
Initialize the scheduler.
Read the config section from the configuration
Reimplemented from marlinmt::Component.
Reimplemented in marlinmt::concurrency::PEPScheduler, and marlinmt::SimpleScheduler.
Definition at line 15 of file IScheduler.cc.
References marlinmt::Component::application(), marlinmt::Application::configuration(), and marlinmt::Component::setParameters().
Referenced by marlinmt::SimpleScheduler::initialize(), and marlinmt::concurrency::PEPScheduler::initialize().
popFinishedEvents()
virtual void marlinmt::IScheduler::popFinishedEvents (std::vector< std::shared_ptr< EventStore >> & events) pure virtual
Retrieve finished events from the scheduler.
Parameters
events the list of event to retrieve
Implemented in marlinmt::concurrency::PEPScheduler, and marlinmt::SimpleScheduler.
processRunHeader()
virtual void marlinmt::IScheduler::processRunHeader (std::shared_ptr< RunHeader > rhdr) pure virtual
Process a run header.
Parameters
rhdr the run header to process
Implemented in marlinmt::concurrency::PEPScheduler, and marlinmt::SimpleScheduler.
pushEvent()
virtual void marlinmt::IScheduler::pushEvent (std::shared_ptr< EventStore > event) pure virtual
Push a new event to the scheduler for processing.
Parameters
event the event to push
Implemented in marlinmt::concurrency::PEPScheduler, and marlinmt::SimpleScheduler.
The documentation for this class was generated from the following files:
IScheduler.h
IScheduler.cc