MarlinMT: marlinmt::concurrency::PEPScheduler Class Reference
marlinmt::concurrency::PEPScheduler Class Reference
PEPScheduler class Parallel Event Processing Scheduler.
#include <PEPScheduler.h>
Inherits marlinmt::IScheduler.
Public Types
using ConditionsMap = std::map< std::string, std::string >
using InputType = std::shared_ptr< EventStore >
using OutputType = WorkerOutput
using WorkerPool = ThreadPool< InputType, OutputType >
using ProcessorSequence = std::shared_ptr< SuperSequence >
using PushResultList = std::vector< WorkerPool::PushResult >
using EventList = std::vector< std::shared_ptr< EventStore > >
using Clock = std::chrono::steady_clock
using TimePoint = std::chrono::steady_clock::time_point
Public Types inherited from marlinmt::Component
using LoggerPtr = Logging::Logger
Public Types inherited from marlinmt::Configurable
using ParameterMap = std::map< std::string, std::shared_ptr< ParameterImpl > >
using iterator = ParameterMap::iterator
using const_iterator = ParameterMap::const_iterator
Public Member Functions
PEPScheduler ()
Constructor.
void initialize () override
Initialize the scheduler.
void end () override
Terminate the scheduler activites Cleanup memory, etc ...
void processRunHeader (std::shared_ptr< RunHeader > rhdr) override
Process a run header.
void pushEvent (std::shared_ptr< EventStore > event) override
Push a new event to the scheduler for processing.
void popFinishedEvents (std::vector< std::shared_ptr< EventStore >> &events) override
Retrieve finished events from the scheduler.
std::size_t freeSlots () const override
Get the number of free event slots.
Public Member Functions inherited from marlinmt::IScheduler
IScheduler ()
Constructor.
virtual ~IScheduler ()=default
Public Member Functions inherited from marlinmt::Component
Component ()=delete
No default constructor.
Component (const Component &)=delete
No copy or assignement.
Component & operator= (const Component &)=delete
virtual ~Component ()=default
Default destructor.
Component (const std::string &type)
Constructor with component type.
const std::string & type () const
Get the component name.
const std::string & name () const
Get the component name.
void setName (const std::string &n)
Set the component name.
const std::string & description () const
Get the component description.
void setDescription (const std::string &desc)
Set the component description.
const Application & application () const
Get the application in which the component is registered.
Application & application ()
Get the application in which the component is registered.
template<class T >
Logging::StreamType log () const
Log a message with specific log level.
Logging::StreamType debug () const
Shortcut for log<DEBUG>()
Logging::StreamType message () const
Shortcut for log<MESSAGE>()
Logging::StreamType warning () const
Shortcut for log<WARNING>()
Logging::StreamType error () const
Shortcut for log<ERROR>()
void setVerbosity (const std::string &level)
Set the verbosity level.
const std::string & verbosity () const
Get the verbosity level.
bool isInitialized () const
Whether the component has been initialized.
void setup (Application *app)
Setup the component.
void printParameters () const
Print the component parameters.
template<class T >
void printParameters () const
Print the component parameters at specific verbosity.
void setParameters (const ConfigSection &section, bool throwIfNotFound=false)
Set the parameters from the configuration section.
void getParameters (ConfigSection &section, const std::set< std::string > &exclude={}) const
Get the parameters from configurable object and populate the config section with.
Public Member Functions inherited from marlinmt::Configurable
Configurable ()=default
virtual ~Configurable ()=default
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value)
Add a parameter.
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value, T defVal)
Add a parameter.
template<typename T >
T parameter (const std::string &name) const
Get a parameter value.
template<typename T >
T parameter (const std::string &name, const T &fallback) const
Get a parameter value.
void checkParameter (const std::string &name) const
Check if the parameter has been registered.
bool exists (const std::string &name) const
Return true if the parameter has been registered.
bool isSet (const std::string &name) const
Returns true if the parameter exists and is set, false otherwise.
void clear ()
Remove all parameters.
void unset ()
Unset all registered parameters.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Private Member Functions
void preConfigure ()
void configureProcessors ()
void configurePool ()
Private Attributes
WorkerPool _pool {}
< The worker thread pool
ProcessorSequence _superSequence {nullptr}
The list of worker output promises.
PushResultList _pushResults {}
The start time.
clock::time_point _startTime {}
The end time.
clock::time_point _endTime {}
The total time spent on processing run headers.
clock::duration_rep _runHeaderTime {0}
The total time spent on locking on thread pool queue access.
clock::duration_rep _lockingTime {0}
The total time spent on popping events from the output event pool.
clock::duration_rep _popTime {0}
UIntParameter _queueSize {*this, "EventQueueSize", "The input event queue size (default 2*nthreads)"}
The scheduler event queue size.
Additional Inherited Members
Protected Attributes inherited from marlinmt::Component
std::string _type {}
The component type.
std::string _name {}
The component name.
std::string _description {"No description"}
The component description.
Application * _application {nullptr}
The application in which the component has been registered.
LoggerPtr _logger {nullptr}
The logger instance.
StringParameter _verbosity { *this, "Verbosity", "The component verbosity level", "MESSAGE" }
The verbosity level of the logger (parameter)
Protected Attributes inherited from marlinmt::Configurable
ParameterMap _parameters {}
The parameter map.
Detailed Description
PEPScheduler class Parallel Event Processing Scheduler.
Implements the scheduling of parallel inter-event processing.
A set of N worker threads are allocated at startup within a thread pool. Every time a new event is pushed in the scheduler, the event is queued in the thread pool for further processing. Note that this operation can fail if the thread pool queue is full. Use freeSlots() to know how many slots are free in the thread pool queue and avoid unexpected exceptions.
Definition at line 45 of file PEPScheduler.h.
Member Typedef Documentation
Clock
using marlinmt::concurrency::PEPScheduler::Clock = std::chrono::steady_clock
Definition at line 54 of file PEPScheduler.h.
ConditionsMap
using marlinmt::concurrency::PEPScheduler::ConditionsMap = std::map<std::string, std::string>
Definition at line 47 of file PEPScheduler.h.
EventList
using marlinmt::concurrency::PEPScheduler::EventList = std::vector<std::shared_ptr<EventStore> >
Definition at line 53 of file PEPScheduler.h.
InputType
using marlinmt::concurrency::PEPScheduler::InputType = std::shared_ptr<EventStore>
Definition at line 48 of file PEPScheduler.h.
OutputType
using marlinmt::concurrency::PEPScheduler::OutputType = WorkerOutput
Definition at line 49 of file PEPScheduler.h.
ProcessorSequence
using marlinmt::concurrency::PEPScheduler::ProcessorSequence = std::shared_ptr<SuperSequence>
Definition at line 51 of file PEPScheduler.h.
PushResultList
using marlinmt::concurrency::PEPScheduler::PushResultList = std::vector<WorkerPool::PushResult>
Definition at line 52 of file PEPScheduler.h.
TimePoint
using marlinmt::concurrency::PEPScheduler::TimePoint = std::chrono::steady_clock::time_point
Definition at line 55 of file PEPScheduler.h.
WorkerPool
using marlinmt::concurrency::PEPScheduler::WorkerPool = ThreadPool<InputType,OutputType>
Definition at line 50 of file PEPScheduler.h.
Constructor & Destructor Documentation
PEPScheduler()
marlinmt::concurrency::PEPScheduler::PEPScheduler ()
Constructor.
Definition at line 76 of file PEPScheduler.cc.
References marlinmt::Component::setName().
Member Function Documentation
configurePool()
void marlinmt::concurrency::PEPScheduler::configurePool () private
Definition at line 170 of file PEPScheduler.cc.
References _pool, _queueSize, _superSequence, marlinmt::concurrency::ThreadPool< IN, OUT >::addWorker(), marlinmt::ParameterBase< T >::get(), marlinmt::ParameterBase< T >::isSet(), marlinmt::concurrency::ThreadPool< IN, OUT >::setAcceptPush(), marlinmt::concurrency::ThreadPool< IN, OUT >::setMaxQueueSize(), and marlinmt::concurrency::ThreadPool< IN, OUT >::start().
Referenced by initialize().
configureProcessors()
void marlinmt::concurrency::PEPScheduler::configureProcessors () private
Definition at line 144 of file PEPScheduler.cc.
References _superSequence, marlinmt::Component::application(), marlinmt::Application::configuration(), MARLINMT_THROW, marlinmt::ConfigSection::parameterNames(), and marlinmt::Configuration::section().
Referenced by initialize().
end()
void marlinmt::concurrency::PEPScheduler::end () override virtual
Terminate the scheduler activites Cleanup memory, etc ...
Implements marlinmt::IScheduler.
Definition at line 94 of file PEPScheduler.cc.
References _endTime, _lockingTime, marlinmt::Component::_logger, _pool, _popTime, _pushResults, _runHeaderTime, _startTime, _superSequence, marlinmt::Component::error(), marlinmt::Component::message(), marlinmt::clock::now(), popFinishedEvents(), marlinmt::concurrency::ThreadPool< IN, OUT >::stop(), and marlinmt::clock::time_difference().
freeSlots()
std::size_t marlinmt::concurrency::PEPScheduler::freeSlots () const override virtual
Get the number of free event slots.
Implements marlinmt::IScheduler.
Definition at line 243 of file PEPScheduler.cc.
References _pool, and marlinmt::concurrency::ThreadPool< IN, OUT >::freeSlots().
initialize()
void marlinmt::concurrency::PEPScheduler::initialize () override virtual
Initialize the scheduler.
Read the config section from the configuration
Reimplemented from marlinmt::IScheduler.
Definition at line 83 of file PEPScheduler.cc.
References _startTime, configurePool(), configureProcessors(), marlinmt::IScheduler::initialize(), marlinmt::clock::now(), and preConfigure().
popFinishedEvents()
void marlinmt::concurrency::PEPScheduler::popFinishedEvents (std::vector< std::shared_ptr< EventStore >> & events) override virtual
Retrieve finished events from the scheduler.
Parameters
events the list of event to retrieve
Implements marlinmt::IScheduler.
Definition at line 220 of file PEPScheduler.cc.
References _popTime, _pushResults, marlinmt::Component::message(), and marlinmt::clock::now().
Referenced by end().
preConfigure()
void marlinmt::concurrency::PEPScheduler::preConfigure () private
Definition at line 136 of file PEPScheduler.cc.
References marlinmt::CmdLineParser::ParseResult::_nthreads, _superSequence, marlinmt::Component::application(), marlinmt::Application::cmdLineParseResult(), and marlinmt::details::nthreads().
Referenced by initialize().
processRunHeader()
void marlinmt::concurrency::PEPScheduler::processRunHeader (std::shared_ptr< RunHeader > rhdr) override virtual
Process a run header.
Parameters
rhdr the run header to process
Implements marlinmt::IScheduler.
Definition at line 190 of file PEPScheduler.cc.
References _pool, _runHeaderTime, _superSequence, marlinmt::concurrency::ThreadPool< IN, OUT >::active(), marlinmt::clock::now(), and marlinmt::concurrency::ThreadPool< IN, OUT >::setAcceptPush().
pushEvent()
void marlinmt::concurrency::PEPScheduler::pushEvent (std::shared_ptr< EventStore > event) override virtual
Push a new event to the scheduler for processing.
Parameters
event the event to push
Implements marlinmt::IScheduler.
Definition at line 211 of file PEPScheduler.cc.
References _lockingTime, _pool, _pushResults, marlinmt::clock::now(), and marlinmt::concurrency::ThreadPool< IN, OUT >::push().
Member Data Documentation
_endTime
clock::time_point marlinmt::concurrency::PEPScheduler::_endTime {} private
The total time spent on processing run headers.
Definition at line 84 of file PEPScheduler.h.
Referenced by end().
_lockingTime
clock::duration_rep marlinmt::concurrency::PEPScheduler::_lockingTime {0} private
The total time spent on popping events from the output event pool.
Definition at line 88 of file PEPScheduler.h.
Referenced by end(), and pushEvent().
_pool
WorkerPool marlinmt::concurrency::PEPScheduler::_pool {} private
< The worker thread pool
The processor super sequence
Definition at line 76 of file PEPScheduler.h.
Referenced by configurePool(), end(), freeSlots(), processRunHeader(), and pushEvent().
_popTime
clock::duration_rep marlinmt::concurrency::PEPScheduler::_popTime {0} private
Definition at line 90 of file PEPScheduler.h.
Referenced by end(), and popFinishedEvents().
_pushResults
PushResultList marlinmt::concurrency::PEPScheduler::_pushResults {} private
The start time.
Definition at line 80 of file PEPScheduler.h.
Referenced by end(), popFinishedEvents(), and pushEvent().
_queueSize
UIntParameter marlinmt::concurrency::PEPScheduler::_queueSize {*this, "EventQueueSize", "The input event queue size (default 2*nthreads)"} private
The scheduler event queue size.
Definition at line 92 of file PEPScheduler.h.
Referenced by configurePool().
_runHeaderTime
clock::duration_rep marlinmt::concurrency::PEPScheduler::_runHeaderTime {0} private
The total time spent on locking on thread pool queue access.
Definition at line 86 of file PEPScheduler.h.
Referenced by end(), and processRunHeader().
_startTime
clock::time_point marlinmt::concurrency::PEPScheduler::_startTime {} private
The end time.
Definition at line 82 of file PEPScheduler.h.
Referenced by end(), and initialize().
_superSequence
ProcessorSequence marlinmt::concurrency::PEPScheduler::_superSequence {nullptr} private
The list of worker output promises.
Definition at line 78 of file PEPScheduler.h.
Referenced by configurePool(), configureProcessors(), end(), preConfigure(), and processRunHeader().
The documentation for this class was generated from the following files:
PEPScheduler.h
PEPScheduler.cc