MarlinMT: marlinmt::book::EntryDataBase< types::HistT< Config > > Class Template Reference
marlinmt::book::EntryDataBase< types::HistT< Config > > Class Template Reference
Base for Histogram EntryData.
#include <HistEntryDataBase.h>
Inherits marlinmt::book::EntryDataBase< void >.
Inherited by marlinmt::book::EntryData< types::HistT< Config >, 0 >.
Public Member Functions
EntryDataBase (const std::string_view &title=empty)
EntryData< Type, Flags::value(Flags::Book::Single) > single () const
construct EntryData for single booking.
EntryData< Type, Flags::value(Flags::Book::MultiCopy) > multiCopy (std::size_t n) const
construct EntryData for multi copy booking.
EntryData< Type, Flags::value(Flags::Book::MultiShared) > multiShared (std::size_t n=0) const
construct EntryData for multi shared booking.
Public Member Functions inherited from marlinmt::book::EntryDataBase< void >
EntryDataBase ()=default
EntryDataBase (const EntryDataBase &)=delete
EntryDataBase & operator= (const EntryDataBase &)=delete
EntryDataBase (EntryDataBase< void > &&)=delete
EntryDataBase & operator= (EntryDataBase &&)=delete
~EntryDataBase ()=default
Protected Types
using Type = types::HistT< Config >
Protected Member Functions
const std::string_view & title () const
read access for passed title.
std::unique_ptr< typename Type::AxisConfig_t > & axis (const std::size_t id)
access Histogram axis configuration.
const std::unique_ptr< typename Type::AxisConfig_t > & axis (const std::size_t id) const
access Histogram axis configuration.
Static Protected Attributes
static constexpr int D = Type::Dimension
Private Attributes
const std::string_view & _title
Histogram custom title, length = 0 when nothing setted.
std::array< std::unique_ptr< typename Type::AxisConfig_t >, D > _axis {}
Histogram axis configuration.
Static Private Attributes
static constexpr std::string_view empty {""}
Friends
template<typename , unsigned long long>
class EntryData
Detailed Description
template<class Config>
class marlinmt::book::EntryDataBase< types::HistT< Config > >
Base for Histogram EntryData.
Definition at line 17 of file HistEntryDataBase.h.
Member Typedef Documentation
Type
template<class Config > using marlinmt::book::EntryDataBase< types::HistT< Config > >::Type = types::HistT<Config> protected
Definition at line 24 of file HistEntryDataBase.h.
Constructor & Destructor Documentation
EntryDataBase()
template<typename Config > marlinmt::book::EntryDataBase< types::HistT< Config > >::EntryDataBase (const std::string_view & title = empty) explicit
Definition at line 17 of file Hist.h.
References marlinmt::book::Flags::Book::Single(), and marlinmt::book::Flags::value().
Member Function Documentation
axis() [1/2]
template<class Config > std::unique_ptr< typename Type::AxisConfig_t >& marlinmt::book::EntryDataBase< types::HistT< Config > >::axis (const std::size_t id) inline protected
access Histogram axis configuration.
Parameters
id of axis, start by 0.
Definition at line 61 of file HistEntryDataBase.h.
axis() [2/2]
template<class Config > const std::unique_ptr< typename Type::AxisConfig_t >& marlinmt::book::EntryDataBase< types::HistT< Config > >::axis (const std::size_t id) const inline protected
access Histogram axis configuration.
Can't Modified.
Parameters
id of axis, start by 0.
Definition at line 70 of file HistEntryDataBase.h.
multiCopy()
template<typename Config > EntryData< types::HistT< Config >, Flags::value(Flags::Book::MultiCopy) > marlinmt::book::EntryDataBase< types::HistT< Config > >::multiCopy (std::size_t n) const
construct EntryData for multi copy booking.
Parameters
n number of memory instances which should be constructed
Definition at line 34 of file Hist.h.
References marlinmt::book::Flags::Book::MultiCopy(), marlinmt::book::Flags::Book::MultiShared(), and marlinmt::book::Flags::value().
multiShared()
template<typename Config > EntryData< types::HistT< Config >, Flags::value(Flags::Book::MultiShared) > marlinmt::book::EntryDataBase< types::HistT< Config > >::multiShared (std::size_t n = 0) const
construct EntryData for multi shared booking.
Definition at line 43 of file Hist.h.
References marlinmt::book::Flags::Book::MultiShared(), and marlinmt::book::Flags::value().
single()
template<typename Config > EntryData< types::HistT< Config >, Flags::value(Flags::Book::Single) > marlinmt::book::EntryDataBase< types::HistT< Config > >::single () const
construct EntryData for single booking.
Definition at line 25 of file Hist.h.
References marlinmt::book::Flags::Book::MultiCopy(), marlinmt::book::Flags::Book::Single(), and marlinmt::book::Flags::value().
title()
template<class Config > const std::string_view& marlinmt::book::EntryDataBase< types::HistT< Config > >::title () const inline protected
read access for passed title.
Definition at line 54 of file HistEntryDataBase.h.
Friends And Related Function Documentation
EntryData
template<class Config > template<typename , unsigned long long> friend class EntryData friend
Definition at line 20 of file HistEntryDataBase.h.
Member Data Documentation
_axis
template<class Config > std::array< std::unique_ptr< typename Type::AxisConfig_t >, D > marlinmt::book::EntryDataBase< types::HistT< Config > >::_axis {} private
Histogram axis configuration.
Definition at line 78 of file HistEntryDataBase.h.
_title
template<class Config > const std::string_view& marlinmt::book::EntryDataBase< types::HistT< Config > >::_title private
Histogram custom title, length = 0 when nothing setted.
Definition at line 76 of file HistEntryDataBase.h.
D
template<class Config > constexpr int marlinmt::book::EntryDataBase< types::HistT< Config > >::D = Type::Dimension static protected
Definition at line 25 of file HistEntryDataBase.h.
empty
template<class Config > constexpr std::string_view marlinmt::book::EntryDataBase< types::HistT< Config > >::empty {""} static private
Definition at line 21 of file HistEntryDataBase.h.
The documentation for this class was generated from the following files:
HistEntryDataBase.h
Hist.h