MarlinMT: marlinmt::concurrency::WorkerBase< IN, void > Class Template Reference
marlinmt::concurrency::WorkerBase< IN, void > Class Template Reference abstract
#include <Worker.h>
Public Member Functions
virtual ~WorkerBase ()=default
virtual void process (IN &&data)=0
Protected Member Functions
void processElement (QueueElement< IN, void > &element)
Friends
class Worker< IN, void >
Detailed Description
template<typename IN>
class marlinmt::concurrency::WorkerBase< IN, void >
Definition at line 78 of file Worker.h.
Constructor & Destructor Documentation
~WorkerBase()
template<typename IN > virtual marlinmt::concurrency::WorkerBase< IN, void >::~WorkerBase () virtual default
Member Function Documentation
process()
template<typename IN > virtual void marlinmt::concurrency::WorkerBase< IN, void >::process (IN && data) pure virtual
processElement()
template<typename IN > void marlinmt::concurrency::WorkerBase< IN, void >::processElement (QueueElement< IN, void > & element) inline protected
Definition at line 107 of file Worker.h.
References marlinmt::concurrency::WorkerBase< IN, OUT >::process(), marlinmt::concurrency::QueueElement< IN, void >::setValue(), and marlinmt::concurrency::QueueElement< IN, void >::takeInput().
Friends And Related Function Documentation
Worker< IN, void >
template<typename IN > friend class Worker< IN, void > friend
Definition at line 79 of file Worker.h.
The documentation for this class was generated from the following file:
Worker.h