MarlinMT: marlinmt::Application Class Reference
marlinmt::Application Class Reference
Application class Base application interface for running a Marlin application.
#include <Application.h>
Public Types
using Logger = Logging::Logger
using CmdLineParseResult = CmdLineParser::ParseResult
using Scheduler = std::shared_ptr< IScheduler >
using EventList = std::vector< std::shared_ptr< EventStore > >
using DataSource = std::shared_ptr< DataSourcePlugin >
using ConditionsMap = std::map< std::string, std::string >
Public Member Functions
Application ()=default
~Application ()=default
void init (int argc, char **argv)
Initialize the application.
void run ()
Run the application.
const CmdLineParseResult & cmdLineParseResult () const
Get the command line parsing result (after init)
const std::string & programName () const
Get the program name.
bool isInitialized () const
Whether the application has been initialized.
Logger logger () const
Get the application logger instance.
Logger createLogger (const std::string &name) const
Create a new logger instance.
const GeometryManager & geometryManager () const
Get the geometry manager.
const RandomSeedManager & randomSeedManager () const
Get the random seed manager.
RandomSeedManager & randomSeedManager ()
Get the random seed manager.
BookStoreManager & bookStoreManager ()
Get book store manager.
const BookStoreManager & bookStoreManager () const
Get book store manager.
const Configuration & configuration () const
Get the main application configuration object.
Static Public Member Functions
static int main (int argc, char **argv)
Create and run an application.
Private Member Functions
void onEventRead (std::shared_ptr< EventStore > event)
Callback function to process an event received from the data source.
void onRunHeaderRead (std::shared_ptr< RunHeader > rhdr)
Callback function to process a run header received from the data source.
void processFinishedEvents (const EventList &events) const
Processed finished events from the output queue.
void dumpExampleConfig ()
Dump an example configuation.
Private Attributes
CmdLineParser::ParseResult _parseResult {}
The command line parse result.
Configuration _configuration {}
The main application configuration.
GeometryManager _geometryMgr {}
The geometry manager.
RandomSeedManager _randomSeedMgr {}
The random seed manager.
LoggerManager _loggerMgr {}
The logger manager.
BookStoreManager _bookStoreManager {}
Managed data object shared between threads.
bool _initialized {false}
Whether the application has been initialized.
Scheduler _scheduler {nullptr}
The event processing scheduler instance.
DataSource _dataSource {nullptr}
The data source plugin.
ConditionsMap _conditions {}
Initial processor runtime conditions from steering file.
Detailed Description
Application class Base application interface for running a Marlin application.
See daughter classes for details.
Definition at line 25 of file Application.h.
Member Typedef Documentation
CmdLineParseResult
using marlinmt::Application::CmdLineParseResult = CmdLineParser::ParseResult
Definition at line 28 of file Application.h.
ConditionsMap
using marlinmt::Application::ConditionsMap = std::map<std::string, std::string>
Definition at line 32 of file Application.h.
DataSource
using marlinmt::Application::DataSource = std::shared_ptr<DataSourcePlugin>
Definition at line 31 of file Application.h.
EventList
using marlinmt::Application::EventList = std::vector<std::shared_ptr<EventStore> >
Definition at line 30 of file Application.h.
Logger
using marlinmt::Application::Logger = Logging::Logger
Definition at line 27 of file Application.h.
Scheduler
using marlinmt::Application::Scheduler = std::shared_ptr<IScheduler>
Definition at line 29 of file Application.h.
Constructor & Destructor Documentation
Application()
marlinmt::Application::Application () default
~Application()
marlinmt::Application::~Application () default
Member Function Documentation
bookStoreManager() [1/2]
BookStoreManager & marlinmt::Application::bookStoreManager ()
Get book store manager.
Definition at line 266 of file Application.cc.
Referenced by marlinmt::ProcessorApi::Book::bookHist1D(), marlinmt::ProcessorApi::Book::bookHist1F(), marlinmt::ProcessorApi::Book::bookHist1I(), marlinmt::ProcessorApi::Book::bookHist2D(), marlinmt::ProcessorApi::Book::bookHist2F(), marlinmt::ProcessorApi::Book::bookHist2I(), marlinmt::ProcessorApi::Book::bookHist3D(), marlinmt::ProcessorApi::Book::bookHist3F(), marlinmt::ProcessorApi::Book::bookHist3I(), marlinmt::ProcessorApi::Book::dontWrite(), marlinmt::ProcessorApi::Book::getHist1D(), marlinmt::ProcessorApi::Book::getHist1F(), marlinmt::ProcessorApi::Book::getHist1I(), marlinmt::ProcessorApi::Book::getHist2D(), marlinmt::ProcessorApi::Book::getHist2F(), marlinmt::ProcessorApi::Book::getHist2I(), marlinmt::ProcessorApi::Book::getHist3D(), marlinmt::ProcessorApi::Book::getHist3F(), marlinmt::ProcessorApi::Book::getHist3I(), and marlinmt::ProcessorApi::Book::write().
bookStoreManager() [2/2]
const BookStoreManager & marlinmt::Application::bookStoreManager () const
Get book store manager.
For const object.
Returns
const ref to book store manager.
Definition at line 272 of file Application.cc.
cmdLineParseResult()
const Application::CmdLineParseResult & marlinmt::Application::cmdLineParseResult () const
Get the command line parsing result (after init)
Definition at line 165 of file Application.cc.
Referenced by marlinmt::BookStoreManager::bookHist(), and marlinmt::concurrency::PEPScheduler::preConfigure().
configuration()
const Configuration & marlinmt::Application::configuration () const
Get the main application configuration object.
Definition at line 278 of file Application.cc.
Referenced by marlinmt::concurrency::PEPScheduler::configureProcessors(), marlinmt::SimpleScheduler::initialize(), marlinmt::IScheduler::initialize(), marlinmt::BookStoreManager::initialize(), marlinmt::LoggerManager::initialize(), marlinmt::GeometryManager::initialize(), marlinmt::GeometryPlugin::initialize(), marlinmt::DataSourcePlugin::initialize(), and marlinmt::Processor::initialize().
createLogger()
Application::Logger marlinmt::Application::createLogger (const std::string & name) const
Create a new logger instance.
If the logger manager is initialized, the logger will share the same sinks as the main logger, else a fresh new logger is created.
Parameters
name the logger name
Definition at line 189 of file Application.cc.
Referenced by marlinmt::Component::setup().
dumpExampleConfig()
void marlinmt::Application::dumpExampleConfig () private
Dump an example configuation.
Definition at line 284 of file Application.cc.
References marlinmt::Configuration::createSection(), marlinmt::Component::getParameters(), marlinmt::Component::setName(), and marlinmt::ConfigSection::setParameter().
geometryManager()
const GeometryManager & marlinmt::Application::geometryManager () const
Get the geometry manager.
Definition at line 237 of file Application.cc.
Referenced by marlinmt::ProcessorApi::geometry().
init()
void marlinmt::Application::init (int argc, char ** argv)
Initialize the application.
Parameters
argc argc from main function
argv argv from main function
Definition at line 52 of file Application.cc.
References MARLINMT_THROW, marlinmt::CmdLineParser::parse(), and marlinmt::details::print_banner().
Referenced by main().
isInitialized()
bool marlinmt::Application::isInitialized () const
Whether the application has been initialized.
Definition at line 177 of file Application.cc.
logger()
Application::Logger marlinmt::Application::logger () const
Get the application logger instance.
Definition at line 183 of file Application.cc.
Referenced by main().
main()
int marlinmt::Application::main (int argc, char ** argv) static
Create and run an application.
Parameters
argc argc from main function
argv argv from main function
Definition at line 24 of file Application.cc.
References init(), logger(), run(), and marlinmt::Exception::what().
onEventRead()
void marlinmt::Application::onEventRead (std::shared_ptr< EventStore > event) private
Callback function to process an event received from the data source.
Parameters
event the event to process
Definition at line 200 of file Application.cc.
onRunHeaderRead()
void marlinmt::Application::onRunHeaderRead (std::shared_ptr< RunHeader > rhdr) private
Callback function to process a run header received from the data source.
Parameters
rhdr the run header to process
Definition at line 230 of file Application.cc.
processFinishedEvents()
void marlinmt::Application::processFinishedEvents (const EventList & events) const private
Processed finished events from the output queue.
Parameters
events the list of finished events
Definition at line 255 of file Application.cc.
programName()
const std::string & marlinmt::Application::programName () const
Get the program name.
Definition at line 171 of file Application.cc.
References marlinmt::CmdLineParser::ParseResult::_programName.
randomSeedManager() [1/2]
const RandomSeedManager & marlinmt::Application::randomSeedManager () const
Get the random seed manager.
Definition at line 243 of file Application.cc.
Referenced by marlinmt::ProcessorApi::registerForRandomSeeds().
randomSeedManager() [2/2]
RandomSeedManager & marlinmt::Application::randomSeedManager ()
Get the random seed manager.
Definition at line 249 of file Application.cc.
run()
void marlinmt::Application::run ()
Run the application.
Definition at line 138 of file Application.cc.
Referenced by main().
Member Data Documentation
_bookStoreManager
BookStoreManager marlinmt::Application::_bookStoreManager {} private
Managed data object shared between threads.
Definition at line 160 of file Application.h.
_conditions
ConditionsMap marlinmt::Application::_conditions {} private
Initial processor runtime conditions from steering file.
Definition at line 168 of file Application.h.
_configuration
Configuration marlinmt::Application::_configuration {} private
The main application configuration.
Definition at line 152 of file Application.h.
_dataSource
DataSource marlinmt::Application::_dataSource {nullptr} private
The data source plugin.
Definition at line 166 of file Application.h.
_geometryMgr
GeometryManager marlinmt::Application::_geometryMgr {} private
The geometry manager.
Definition at line 154 of file Application.h.
_initialized
bool marlinmt::Application::_initialized {false} private
Whether the application has been initialized.
Definition at line 162 of file Application.h.
_loggerMgr
LoggerManager marlinmt::Application::_loggerMgr {} private
The logger manager.
Definition at line 158 of file Application.h.
_parseResult
CmdLineParser::ParseResult marlinmt::Application::_parseResult {} private
The command line parse result.
Definition at line 150 of file Application.h.
_randomSeedMgr
RandomSeedManager marlinmt::Application::_randomSeedMgr {} private
The random seed manager.
Definition at line 156 of file Application.h.
_scheduler
Scheduler marlinmt::Application::_scheduler {nullptr} private
The event processing scheduler instance.
Definition at line 164 of file Application.h.
The documentation for this class was generated from the following files:
Application.h
Application.cc