MarlinMT: marlinmt::TestProcessor Class Reference
marlinmt::TestProcessor Class Reference
Simple processor for testing.
Inherits marlinmt::Processor.
Public Member Functions
TestProcessor ()
void init () override
Called at the begin of the job before anything is read.
void processRunHeader (RunHeader *run) override
Called for every run.
void processEvent (EventStore *evt) override
Called for every event - the working horse.
void end () override
Called after data processing for clean up.
Public Member Functions inherited from marlinmt::Processor
virtual ~Processor ()=default
Processor (const std::string &t)
Constructor.
std::optional< bool > runtimeOption (ERuntimeOption option) const
Get the forced runtime option settings.
Public Member Functions inherited from marlinmt::Component
Component ()=delete
No default constructor.
Component (const Component &)=delete
No copy or assignement.
Component & operator= (const Component &)=delete
virtual ~Component ()=default
Default destructor.
Component (const std::string &type)
Constructor with component type.
const std::string & type () const
Get the component name.
const std::string & name () const
Get the component name.
void setName (const std::string &n)
Set the component name.
const std::string & description () const
Get the component description.
void setDescription (const std::string &desc)
Set the component description.
const Application & application () const
Get the application in which the component is registered.
Application & application ()
Get the application in which the component is registered.
template<class T >
Logging::StreamType log () const
Log a message with specific log level.
Logging::StreamType debug () const
Shortcut for log<DEBUG>()
Logging::StreamType message () const
Shortcut for log<MESSAGE>()
Logging::StreamType warning () const
Shortcut for log<WARNING>()
Logging::StreamType error () const
Shortcut for log<ERROR>()
void setVerbosity (const std::string &level)
Set the verbosity level.
const std::string & verbosity () const
Get the verbosity level.
bool isInitialized () const
Whether the component has been initialized.
void setup (Application *app)
Setup the component.
void printParameters () const
Print the component parameters.
template<class T >
void printParameters () const
Print the component parameters at specific verbosity.
void setParameters (const ConfigSection &section, bool throwIfNotFound=false)
Set the parameters from the configuration section.
void getParameters (ConfigSection &section, const std::set< std::string > &exclude={}) const
Get the parameters from configurable object and populate the config section with.
Public Member Functions inherited from marlinmt::Configurable
Configurable ()=default
virtual ~Configurable ()=default
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value)
Add a parameter.
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value, T defVal)
Add a parameter.
template<typename T >
T parameter (const std::string &name) const
Get a parameter value.
template<typename T >
T parameter (const std::string &name, const T &fallback) const
Get a parameter value.
void checkParameter (const std::string &name) const
Check if the parameter has been registered.
bool exists (const std::string &name) const
Return true if the parameter has been registered.
bool isSet (const std::string &name) const
Returns true if the parameter exists and is set, false otherwise.
void clear ()
Remove all parameters.
void unset ()
Unset all registered parameters.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Protected Member Functions
void printEndMessage () const
Test method for const.
Protected Member Functions inherited from marlinmt::Processor
void setRuntimeOption (ERuntimeOption option, bool value)
Force the runtime option to a given boolean value.
Protected Attributes
int _nRun {0}
std::atomic_int _nEvt {0}
bool _doCalibration {false}
Protected Attributes inherited from marlinmt::Component
std::string _type {}
The component type.
std::string _name {}
The component name.
std::string _description {"No description"}
The component description.
Application * _application {nullptr}
The application in which the component has been registered.
LoggerPtr _logger {nullptr}
The logger instance.
StringParameter _verbosity { *this, "Verbosity", "The component verbosity level", "MESSAGE" }
The verbosity level of the logger (parameter)
Protected Attributes inherited from marlinmt::Configurable
ParameterMap _parameters {}
The parameter map.
Additional Inherited Members
Public Types inherited from marlinmt::Processor
enum ERuntimeOption { ERuntimeOption::eCritical, ERuntimeOption::eClone }
ERuntimeOption enumerator.
using RuntimeOptions = std::map< ERuntimeOption, bool >
Public Types inherited from marlinmt::Component
using LoggerPtr = Logging::Logger
Public Types inherited from marlinmt::Configurable
using ParameterMap = std::map< std::string, std::shared_ptr< ParameterImpl > >
using iterator = ParameterMap::iterator
using const_iterator = ParameterMap::const_iterator
Detailed Description
Simple processor for testing.
Writes something to stdout for every callbackmethod.
Input - Prerequisites
none
Output
none
Author
F. Gaede, DESY
Version
Id
TestProcessor.h,v 1.7 2007-05-23 13:12:21 gaede Exp
Definition at line 30 of file TestProcessor.cc.
Constructor & Destructor Documentation
TestProcessor()
marlinmt::TestProcessor::TestProcessor ()
Definition at line 64 of file TestProcessor.cc.
References marlinmt::Component::setDescription().
Member Function Documentation
end()
void marlinmt::TestProcessor::end () override virtual
Called after data processing for clean up.
Reimplemented from marlinmt::Processor.
Definition at line 123 of file TestProcessor.cc.
References printEndMessage().
init()
void marlinmt::TestProcessor::init () override virtual
Called at the begin of the job before anything is read.
Use to initialize the processor, e.g. book histograms.
Reimplemented from marlinmt::Processor.
Definition at line 72 of file TestProcessor.cc.
References marlinmt::Component::name(), and marlinmt::Component::printParameters().
printEndMessage()
void marlinmt::TestProcessor::printEndMessage () const protected
Test method for const.
Definition at line 129 of file TestProcessor.cc.
References _nEvt, _nRun, and MARLINMT_DECLARE_PROCESSOR.
Referenced by end().
processEvent()
void marlinmt::TestProcessor::processEvent (EventStore * evt) override virtual
Called for every event - the working horse.
Reimplemented from marlinmt::Processor.
Definition at line 88 of file TestProcessor.cc.
References _nEvt, marlinmt::ProcessorApi::isFirstEvent(), marlinmt::ProcessorApi::setReturnValue(), marlinmt::EventStore::uid(), and marlinmt::Component::verbosity().
processRunHeader()
void marlinmt::TestProcessor::processRunHeader (RunHeader * run) override virtual
Called for every run.
Reimplemented from marlinmt::Processor.
Definition at line 79 of file TestProcessor.cc.
References _nRun, and marlinmt::RunHeader::runNumber().
Member Data Documentation
_doCalibration
bool marlinmt::TestProcessor::_doCalibration {false} protected
Definition at line 58 of file TestProcessor.cc.
_nEvt
std::atomic_int marlinmt::TestProcessor::_nEvt {0} protected
Definition at line 57 of file TestProcessor.cc.
Referenced by printEndMessage(), and processEvent().
_nRun
int marlinmt::TestProcessor::_nRun {0} protected
Definition at line 56 of file TestProcessor.cc.
Referenced by printEndMessage(), and processRunHeader().
The documentation for this class was generated from the following file:
TestProcessor.cc