MarlinMT: marlinmt::GeometryManager Class Reference
marlinmt::GeometryManager Class Reference
GeometryManager class.
#include <GeometryManager.h>
Inherits marlinmt::Component.
Public Member Functions
GeometryManager (const GeometryManager &)=delete
GeometryManager & operator= (const GeometryManager &)=delete
~GeometryManager ()=default
GeometryManager ()
Default constructor.
template<typename T >
const T * geometry () const
Get the underlying geometry handle Example:
std::type_index typeIndex () const
Get the underlying geometry type info.
void clear ()
Clear the geometry content.
Public Member Functions inherited from marlinmt::Component
Component ()=delete
No default constructor.
Component (const Component &)=delete
No copy or assignement.
Component & operator= (const Component &)=delete
virtual ~Component ()=default
Default destructor.
Component (const std::string &type)
Constructor with component type.
const std::string & type () const
Get the component name.
const std::string & name () const
Get the component name.
void setName (const std::string &n)
Set the component name.
const std::string & description () const
Get the component description.
void setDescription (const std::string &desc)
Set the component description.
const Application & application () const
Get the application in which the component is registered.
Application & application ()
Get the application in which the component is registered.
template<class T >
Logging::StreamType log () const
Log a message with specific log level.
Logging::StreamType debug () const
Shortcut for log<DEBUG>()
Logging::StreamType message () const
Shortcut for log<MESSAGE>()
Logging::StreamType warning () const
Shortcut for log<WARNING>()
Logging::StreamType error () const
Shortcut for log<ERROR>()
void setVerbosity (const std::string &level)
Set the verbosity level.
const std::string & verbosity () const
Get the verbosity level.
bool isInitialized () const
Whether the component has been initialized.
void setup (Application *app)
Setup the component.
void printParameters () const
Print the component parameters.
template<class T >
void printParameters () const
Print the component parameters at specific verbosity.
void setParameters (const ConfigSection &section, bool throwIfNotFound=false)
Set the parameters from the configuration section.
void getParameters (ConfigSection &section, const std::set< std::string > &exclude={}) const
Get the parameters from configurable object and populate the config section with.
Public Member Functions inherited from marlinmt::Configurable
Configurable ()=default
virtual ~Configurable ()=default
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value)
Add a parameter.
template<typename T >
std::shared_ptr< ParameterImpl > addParameter (EParameterType paramType, const std::string &name, const std::string &desc, std::shared_ptr< T > value, T defVal)
Add a parameter.
template<typename T >
T parameter (const std::string &name) const
Get a parameter value.
template<typename T >
T parameter (const std::string &name, const T &fallback) const
Get a parameter value.
void checkParameter (const std::string &name) const
Check if the parameter has been registered.
bool exists (const std::string &name) const
Return true if the parameter has been registered.
bool isSet (const std::string &name) const
Returns true if the parameter exists and is set, false otherwise.
void clear ()
Remove all parameters.
void unset ()
Unset all registered parameters.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Private Member Functions
void initialize () override
Initialize geometry manager.
Private Attributes
std::shared_ptr< GeometryPlugin > _plugin {nullptr}
The geometry plugin created on initialization.
StringParameter _geometryType {*this, "GeometryType", "The geometry plugin type", "EmptyGeometry"}
The geometry type, read as <geometry type="DD4hepGeometry">
Additional Inherited Members
Public Types inherited from marlinmt::Component
using LoggerPtr = Logging::Logger
Public Types inherited from marlinmt::Configurable
using ParameterMap = std::map< std::string, std::shared_ptr< ParameterImpl > >
using iterator = ParameterMap::iterator
using const_iterator = ParameterMap::const_iterator
Protected Attributes inherited from marlinmt::Component
std::string _type {}
The component type.
std::string _name {}
The component name.
std::string _description {"No description"}
The component description.
Application * _application {nullptr}
The application in which the component has been registered.
LoggerPtr _logger {nullptr}
The logger instance.
StringParameter _verbosity { *this, "Verbosity", "The component verbosity level", "MESSAGE" }
The verbosity level of the logger (parameter)
Protected Attributes inherited from marlinmt::Configurable
ParameterMap _parameters {}
The parameter map.
Detailed Description
GeometryManager class.
Handle a user plugin in charge of loading the geometry in the framework and providing access to it.
Definition at line 22 of file GeometryManager.h.
Constructor & Destructor Documentation
GeometryManager() [1/2]
marlinmt::GeometryManager::GeometryManager (const GeometryManager &) delete
~GeometryManager()
marlinmt::GeometryManager::~GeometryManager () default
GeometryManager() [2/2]
marlinmt::GeometryManager::GeometryManager ()
Default constructor.
Definition at line 9 of file GeometryManager.cc.
References marlinmt::Component::setName().
Member Function Documentation
clear()
void marlinmt::GeometryManager::clear ()
Clear the geometry content.
Definition at line 48 of file GeometryManager.cc.
References _plugin.
geometry()
template<typename T > const T * marlinmt::GeometryManager::geometry () const inline
Get the underlying geometry handle Example:
// assume Gear geometry has been loaded
const gear::GearMgr* gearGeo = mgr->geometry<gear::GearMgr>() ;
// assume DD4hep geometry has been loaded
const dd4hep::Detector* dd4hepGeo = mgr->geometry<dd4hep::Detector>() ;
Definition at line 72 of file GeometryManager.h.
References _plugin.
Referenced by marlinmt::ProcessorApi::geometry().
initialize()
void marlinmt::GeometryManager::initialize () override private virtual
Initialize geometry manager.
Reimplemented from marlinmt::Component.
Definition at line 16 of file GeometryManager.cc.
References _geometryType, _plugin, marlinmt::Component::application(), marlinmt::Application::configuration(), marlinmt::ParameterBase< T >::get(), marlinmt::PluginManager::instance(), MARLINMT_THROW, marlinmt::Component::message(), marlinmt::Configuration::section(), and marlinmt::Component::setParameters().
operator=()
GeometryManager& marlinmt::GeometryManager::operator= (const GeometryManager &) delete
typeIndex()
std::type_index marlinmt::GeometryManager::typeIndex () const
Get the underlying geometry type info.
Definition at line 39 of file GeometryManager.cc.
References _plugin, and MARLINMT_THROW.
Member Data Documentation
_geometryType
StringParameter marlinmt::GeometryManager::_geometryType {*this, "GeometryType", "The geometry plugin type", "EmptyGeometry"} private
The geometry type, read as <geometry type="DD4hepGeometry">
Definition at line 65 of file GeometryManager.h.
Referenced by initialize().
_plugin
std::shared_ptr<GeometryPlugin> marlinmt::GeometryManager::_plugin {nullptr} private
The geometry plugin created on initialization.
Definition at line 63 of file GeometryManager.h.
Referenced by clear(), geometry(), initialize(), and typeIndex().
The documentation for this class was generated from the following files:
GeometryManager.h
GeometryManager.cc