MarlinMT: marlinmt::Logging Class Reference
marlinmt::Logging Class Reference
Logging class.
#include <Logging.h>
Public Types
using mutex_type = streamlog::st
using Logger = std::shared_ptr< streamlog::logstreamT< mutex_type > >
using StreamType = Logger::element_type::stream_type
using DefaultLoggerType = streamlog::logstream::default_logger_type
Static Public Member Functions
static Logger createLogger (const std::string &name)
Create a standalone logger instance.
static DefaultLoggerType & globalLogger ()
Get the global streamlog logger.
Detailed Description
Logging class.
Defines the basic logging functionalities in Marlin. For a more application oriented configuration, see LoggerManager.h
Definition at line 66 of file Logging.h.
Member Typedef Documentation
DefaultLoggerType
using marlinmt::Logging::DefaultLoggerType = streamlog::logstream::default_logger_type
Definition at line 75 of file Logging.h.
Logger
using marlinmt::Logging::Logger = std::shared_ptr<streamlog::logstreamT<mutex_type> >
Definition at line 73 of file Logging.h.
mutex_type
using marlinmt::Logging::mutex_type = streamlog::st
Definition at line 71 of file Logging.h.
StreamType
using marlinmt::Logging::StreamType = Logger::element_type::stream_type
Definition at line 74 of file Logging.h.
Member Function Documentation
createLogger()
Logging::Logger marlinmt::Logging::createLogger (const std::string & name) static
Create a standalone logger instance.
Parameters
name the logger name
Definition at line 5 of file Logging.cc.
Referenced by marlinmt::Component::Component(), marlinmt::LoggerManager::createLogger(), and marlinmt::PluginManager::PluginManager().
globalLogger()
Logging::DefaultLoggerType & marlinmt::Logging::globalLogger () static
Get the global streamlog logger.
Returns a reference
Definition at line 11 of file Logging.cc.
The documentation for this class was generated from the following files:
Logging.h
Logging.cc