MarlinMT: jenkinsHash.h File Reference
jenkinsHash.h File Reference
Macros
#define MARLIN_FALLTHROUGH
#define hashsize(n) (1U << (n))
#define hashmask(n) (hashsize (n) - 1)
#define mix(a, b, c)
Functions
unsigned jenkins_hash (unsigned char *k, unsigned length, unsigned initval)
Macro Definition Documentation
hashmask
#define hashmask (n) (hashsize (n) - 1)
Definition at line 25 of file jenkinsHash.h.
hashsize
#define hashsize (n) (1U << (n))
Definition at line 24 of file jenkinsHash.h.
MARLIN_FALLTHROUGH
#define MARLIN_FALLTHROUGH
Definition at line 11 of file jenkinsHash.h.
Referenced by jenkins_hash().
mix
#define mix (a, b, c)
Value:
{ \
  a -= b; a -= c; a ^= (c>>13); \
  b -= c; b -= a; b ^= (a<<8); \
  c -= a; c -= b; c ^= (b>>13); \
  a -= b; a -= c; a ^= (c>>12);  \
  b -= c; b -= a; b ^= (a<<16); \
  c -= a; c -= b; c ^= (b>>5); \
  a -= b; a -= c; a ^= (c>>3);  \
  b -= c; b -= a; b ^= (a<<10); \
  c -= a; c -= b; c ^= (b>>15); \
}
Definition at line 54 of file jenkinsHash.h.
Referenced by jenkins_hash().
Function Documentation
jenkins_hash()
unsigned jenkins_hash (unsigned char * k, unsigned length, unsigned initval) inline
Definition at line 94 of file jenkinsHash.h.
References MARLIN_FALLTHROUGH, and mix.
Referenced by marlinmt::RandomSeedManager::generateRandomSeeds(), marlinmt::ReaderListener::processEvent(), and marlinmt::StdHepFileSource::readOne().