MarlinMT: marlinmt::book::types Namespace Reference
marlinmt::book::types Namespace Reference
Alias for Types used by MarlinMTBook.
Classes
class AxisConfig
collection for Axis Description
class HistConcurrentFiller
class managing parallel filling to one histogram.
class HistConcurrentFillManager
class managing HistConcurrentFiller creation for one histogram.
struct HistConfig
type trait for Histograms.
class HistT
Generalized histogram class.
Typedefs
using H1F = HistT< HistConfig< double, float, 1 > >
using H1D = HistT< HistConfig< double, double, 1 > >
using H1I = HistT< HistConfig< double, int, 1 > >
using H2F = HistT< HistConfig< double, float, 2 > >
using H2D = HistT< HistConfig< double, double, 2 > >
using H2I = HistT< HistConfig< double, int, 2 > >
using H3F = HistT< HistConfig< double, float, 3 > >
using H3D = HistT< HistConfig< double, double, 3 > >
using H3I = HistT< HistConfig< double, int, 3 > >
Functions
template<typename Config >
HistT< Config > & add (HistT< Config > &to, const HistT< Config > &from)
add weights from one Histogram to an other.
template<typename Config >
void add (const std::shared_ptr< HistT< Config >> &to, const std::shared_ptr< HistT< Config >> &from)
template<typename Config >
auto toRoot6 (const HistT< Config > &hist, const std::string_view &name)
convert histogram to Root-6 Object for serialization
HistConfig_ROOT (H1F, ROOT::Experimental::RH1F, float, 1)
HistConfig_ROOT (H1D, ROOT::Experimental::RH1D, double, 1)
HistConfig_ROOT (H1I, ROOT::Experimental::RH1I, int, 1)
HistConfig_ROOT (H2F, ROOT::Experimental::RH2F, float, 2)
HistConfig_ROOT (H2D, ROOT::Experimental::RH2D, double, 2)
HistConfig_ROOT (H2I, ROOT::Experimental::RH2I, int, 2)
HistConfig_ROOT (H3F, ROOT::Experimental::RH3F, float, 3)
HistConfig_ROOT (H3D, ROOT::Experimental::RH3D, double, 3)
HistConfig_ROOT (H3I, ROOT::Experimental::RH3I, int, 3)
Variables
constexpr std::size_t HistogramFillerBufferSize = MARLIN_HIST_FILLER_BUFFER_SIZE
Buffer size for Histograms used in Shared mode.
Detailed Description
Alias for Types used by MarlinMTBook.
Typedef Documentation
H1D
using marlinmt::book::types::H1D = typedef HistT<HistConfig<double, double , 1> >
Definition at line 77 of file Dummy.h.
H1F
using marlinmt::book::types::H1F = typedef HistT<HistConfig<double, float , 1> >
Definition at line 76 of file Dummy.h.
H1I
using marlinmt::book::types::H1I = typedef HistT<HistConfig<double, int , 1> >
Definition at line 78 of file Dummy.h.
H2D
using marlinmt::book::types::H2D = typedef HistT<HistConfig<double, double , 2> >
Definition at line 80 of file Dummy.h.
H2F
using marlinmt::book::types::H2F = typedef HistT<HistConfig<double, float , 2> >
Definition at line 79 of file Dummy.h.
H2I
using marlinmt::book::types::H2I = typedef HistT<HistConfig<double, int , 2> >
Definition at line 81 of file Dummy.h.
H3D
using marlinmt::book::types::H3D = typedef HistT<HistConfig<double, double , 3> >
Definition at line 83 of file Dummy.h.
H3F
using marlinmt::book::types::H3F = typedef HistT<HistConfig<double, float , 3> >
Definition at line 82 of file Dummy.h.
H3I
using marlinmt::book::types::H3I = typedef HistT<HistConfig<double, int , 3> >
Definition at line 84 of file Dummy.h.
Function Documentation
add() [1/2]
template<typename Config > HistT< Config > & marlinmt::book::types::add (HistT< Config > & to, const HistT< Config > & from)
add weights from one Histogram to an other.
Definition at line 14 of file Dummy.h.
Referenced by marlinmt::book::EntryMultiShared< types::HistT< Config > >::handle().
add() [2/2]
template<typename Config > void marlinmt::book::types::add (const std::shared_ptr< HistT< Config >> & to, const std::shared_ptr< HistT< Config >> & from)
See also
HistT<Config>& add(HistT<Config>& to, const HistT<Config>& from);
Definition at line 19 of file Dummy.h.
References marlinmt::book::types::HistT< Config >::HistT().
HistConfig_ROOT() [1/9]
marlinmt::book::types::HistConfig_ROOT (H1F , ROOT::Experimental::RH1F , float , 1)
HistConfig_ROOT() [2/9]
marlinmt::book::types::HistConfig_ROOT (H1D , ROOT::Experimental::RH1D , double , 1)
HistConfig_ROOT() [3/9]
marlinmt::book::types::HistConfig_ROOT (H1I , ROOT::Experimental::RH1I , int , 1)
HistConfig_ROOT() [4/9]
marlinmt::book::types::HistConfig_ROOT (H2F , ROOT::Experimental::RH2F , float , 2)
HistConfig_ROOT() [5/9]
marlinmt::book::types::HistConfig_ROOT (H2D , ROOT::Experimental::RH2D , double , 2)
HistConfig_ROOT() [6/9]
marlinmt::book::types::HistConfig_ROOT (H2I , ROOT::Experimental::RH2I , int , 2)
HistConfig_ROOT() [7/9]
marlinmt::book::types::HistConfig_ROOT (H3F , ROOT::Experimental::RH3F , float , 3)
HistConfig_ROOT() [8/9]
marlinmt::book::types::HistConfig_ROOT (H3D , ROOT::Experimental::RH3D , double , 3)
HistConfig_ROOT() [9/9]
marlinmt::book::types::HistConfig_ROOT (H3I , ROOT::Experimental::RH3I , int , 3)
toRoot6()
template<typename Config > auto marlinmt::book::types::toRoot6 (const HistT< Config > & hist, const std::string_view & name)
convert histogram to Root-6 Object for serialization
Parameters
hist histogram to convert
name of object.
Definition at line 71 of file Dummy.h.
Referenced by writeObject().
Variable Documentation
HistogramFillerBufferSize
constexpr std::size_t marlinmt::book::types::HistogramFillerBufferSize = MARLIN_HIST_FILLER_BUFFER_SIZE
Buffer size for Histograms used in Shared mode.
larger → less synchronisation points
larger → more memory consumption.
Note
can set with the CMAKE Variable {MARLIN_HIST_FILLER_BUFFER_SIZE}
Definition at line 44 of file ROOTv7.h.