MarlinMT: marlinmt Namespace Reference
marlinmt Namespace Reference
Namespaces
book
contains classes needed to book and managed booked objects.
concurrency
details
extensions
loglevel
validator
Classes
class Application
Application class Base application interface for running a Marlin application.
class BookStoreManager
BookStoreManager class.
class clock
clock class Provide a wrapper around a certain clock type in std to perform safe clock measurement in multi-threading environement
struct ClockMeasure
ClockMeasure struct Holds clock measurement data for processors.
class CmdLineParser
CmdLineParser class Does the main command line parsing for MarlinMT.
class Component
Component class.
class ConfigHelper
ConfigHelper class A simple class with helper methods for configuration.
class ConfigReader
ConfigReader base class Interface for reading configuration.
class ConfigSection
ConfigSection class Holds a set of parameters and subsection.
class Configurable
Configurable class Interface for configuring components in the framework.
class Configuration
Configuration class.
class ConfigWriter
ConfigWriter base class Interface for writing configuration.
class CPUCrunchingProcessor
Simple processor crunching CPU time for n milliseconds.
class DataSourcePlugin
DataSourcePlugin class Responsible for reading/getting LCEvent and LCRunHeader in the framework for further processing.
class DD4hepGeometry
DD4hepGeometry class Responsible for loading DD4hep geometry in MarlinMT.
class DumpEventProcessor
DumpEventProcessor simply dumps an event in the console.
class EmptyGeometry
EmptyGeometry class Implement an empty geometry.
class Entry
class EventSelectorProcessor
Simple event selector processor.
class EventStore
EventStore class.
class Exception
Exception class.
struct Expression
Helper struct for LogicalExpression.
class Extension
class Extensions
Extensions class.
class GearGeometry
GearGeometry class Responsible for loading Gear geometry in MarlinMT.
class GeometryManager
GeometryManager class.
class GeometryPlugin
GeometryPlugin class Responsible for loading geometry in Marlin and providing access to it through the GeometryManager.
class HashHelper
HashHelper class Helper class to generate hash 64 id.
class IScheduler
IScheduler interface Interface for implementing a scheduling algorithm for event processing.
class LCIOEventUnpackingProcessor
Simple processor that triggers the LCEvent data unpacking.
class LCIOFileSource
LCIOFileSource class.
class LCIOOutputProcessor
Default output processor.
class LoggerManager
LoggerManager class Responsible for configuring logger for a given application.
class Logging
Logging class.
class LogicalExpressions
Helper class that holds named boolean values and named conditions that are expressions of these values and computes the corresponding truth values.
class MemoryMonitorProcessor
MemoryMonitorProcessor is a memory monitoring application for Marlin.
class Output
class Parameter
Parameter<T> class High level interface to register simple parameter values (int, float, ...).
class ParameterBase
ParameterBase<T> class Base interface for user parameters.
class ParameterImpl
ParameterImpl class Abstract internal implementation of a parameter.
class PluginManager
PluginManager singleton class Responsible for loading shared libraries and collecting processor factory instances.
class Processor
Processor class.
class ProcessorApi
class ProcessorConditionsExtension
ProcessorConditionsExtension class Event extension providing access to processor runtime conditions (LogicalExpressions)
class RandomSeedExtension
RandomSeedExtension class Event extension providing access to random seeds.
class RandomSeedManager
RandomSeedManager class.
class ReaderListener
ReaderListener class.
class RunHeader
RunHeader class.
class Sequence
Sequence class A sequence is a list of processors wrapped in SequenceItem objects.
class SequenceItem
SequenceItem class Handle a processor pointer and call Processor::processEvent in a critical section if configured accordingly.
class SimpleScheduler
SimpleScheduler class.
class Statusmonitor
Simple processor for writing out a status message every n-th event.
class StdHepFileSource
StdHepFileSource class.
class StringUtil
StringUtil class Simple utility class for string operations.
class SuperSequence
SuperSequence class Manages a fixed list of Sequence objects.
class TestProcessor
Simple processor for testing.
class Tokenizer
Helper class for LogicalExpressions that splits the expression into subexpressions - needs to be apllied iteratively.
class VectorParameter
VectorParameter<T> class.
class XMLConfigReader
XMLConfigReader plugin Read an XML file and populate the configuration with sections and parameters.
class XMLConfigWriter
XMLConfigWriter plugin Write an XML file from the configuration sections and parameters.
Typedefs
template<typename P >
using AxisConfig = book::types::AxisConfig< P >
template<typename P , typename W , std::size_t D>
using HistConfig = book::types::HistConfig< P, W, D >
template<typename P , typename W , std::size_t D>
using HistT = book::types::HistT< HistConfig< P, W, D > >
using BookFlag_t = book::Flag_t
using AxisConfigF = AxisConfig< float >
using AxisConfigD = AxisConfig< double >
using AxisConfigI = AxisConfig< int >
using Hist1F = book::types::H1F
using Hist1D = book::types::H1D
using Hist1I = book::types::H1I
using Hist2F = book::types::H2F
using Hist2D = book::types::H2D
using Hist2I = book::types::H2I
using Hist3F = book::types::H3F
using Hist3D = book::types::H3D
using Hist3I = book::types::H3I
using H1FEntry = book::Handle< book::Entry< Hist1F > >
using H1DEntry = book::Handle< book::Entry< Hist1D > >
using H1IEntry = book::Handle< book::Entry< Hist1I > >
using H2FEntry = book::Handle< book::Entry< Hist2F > >
using H2DEntry = book::Handle< book::Entry< Hist2D > >
using H2IEntry = book::Handle< book::Entry< Hist2I > >
using H3FEntry = book::Handle< book::Entry< Hist3F > >
using H3DEntry = book::Handle< book::Entry< Hist3D > >
using H3IEntry = book::Handle< book::Entry< Hist3I > >
using H1FHandle = book::Handle< Hist1F >
using H1DHandle = book::Handle< Hist1D >
using H1IHandle = book::Handle< Hist1I >
using H2FHandle = book::Handle< Hist2F >
using H2DHandle = book::Handle< Hist2D >
using H2IHandle = book::Handle< Hist2I >
using H3FHandle = book::Handle< Hist3F >
using H3DHandle = book::Handle< Hist3D >
using H3IHandle = book::Handle< Hist3I >
using IntParameter = Parameter< int >
using UIntParameter = Parameter< unsigned int >
using FloatParameter = Parameter< float >
using DoubleParameter = Parameter< double >
using BoolParameter = Parameter< bool >
using StringParameter = Parameter< std::string >
using IntVectorParameter = VectorParameter< int >
using UIntVectorParameter = VectorParameter< unsigned int >
using FloatVectorParameter = VectorParameter< float >
using DoubleVectorParameter = VectorParameter< double >
using BoolVectorParameter = VectorParameter< bool >
using StringVectorParameter = VectorParameter< std::string >
template<typename T >
using ValidatorFunctionT = std::function< bool(const T &)>
Enumerations
enum EParameterType { EParameterType::eSimple, EParameterType::eVector }
EParameterType enumerator Enumerates parameter types supported by Marlin.
Functions
std::ostream & operator<< (std::ostream &stream, const Configuration &cfg)
Stream operator.
MARLINMT_DEFINE_EXCEPTION (SkipEventException)
Definition of Marlin exceptions.
MARLINMT_DEFINE_EXCEPTION (StopProcessingException)
MARLINMT_DEFINE_EXCEPTION (ParseException)
MARLINMT_DEFINE_EXCEPTION (BookStoreException)
std::ostream & operator<< (std::ostream &s, Expression &e)
template<typename T >
std::ostream & operator<< (std::ostream &stream, const Parameter< T > &rhs)
template<typename T , typename S >
bool operator== (const Parameter< T > &lhs, const S &rhs)
template<typename T , typename S >
bool operator!= (const Parameter< T > &lhs, const S &rhs)
template<typename T , typename S >
bool operator< (const Parameter< T > &lhs, const S &rhs)
template<typename T , typename S >
bool operator<= (const Parameter< T > &lhs, const S &rhs)
template<typename T , typename S >
bool operator> (const Parameter< T > &lhs, const S &rhs)
template<typename T , typename S >
bool operator>= (const Parameter< T > &lhs, const S &rhs)
INSTANCIATIONS_HIST (Hist1F)
INSTANCIATIONS_HIST (Hist1D)
INSTANCIATIONS_HIST (Hist1I)
INSTANCIATIONS_HIST (Hist2F)
INSTANCIATIONS_HIST (Hist2D)
INSTANCIATIONS_HIST (Hist2I)
INSTANCIATIONS_HIST (Hist3F)
INSTANCIATIONS_HIST (Hist3D)
INSTANCIATIONS_HIST (Hist3I)
void printSection (const ConfigSection &section, std::ostream &stream, const std::string &prefix)
std::filesystem::path constructPath (const Processor *proc, const std::filesystem::path &path)
construct absolute path from relative path and processor.
template<typename HistT >
book::Handle< book::Entry< HistT > > getObject (const BookStoreManager &storeManager, const std::filesystem::path &path, const std::string_view &name)
Typedef Documentation
AxisConfig
template<typename P > using marlinmt::AxisConfig = typedef book::types::AxisConfig<P>
Definition at line 15 of file MarlinMTBookConfig.h.
AxisConfigD
using marlinmt::AxisConfigD = typedef AxisConfig<double>
Definition at line 31 of file MarlinMTBookConfig.h.
AxisConfigF
using marlinmt::AxisConfigF = typedef AxisConfig<float>
Definition at line 30 of file MarlinMTBookConfig.h.
AxisConfigI
using marlinmt::AxisConfigI = typedef AxisConfig<int>
Definition at line 32 of file MarlinMTBookConfig.h.
BookFlag_t
using marlinmt::BookFlag_t = typedef book::Flag_t
Definition at line 23 of file MarlinMTBookConfig.h.
BoolParameter
using marlinmt::BoolParameter = typedef Parameter<bool>
Definition at line 816 of file Parameter.h.
BoolVectorParameter
using marlinmt::BoolVectorParameter = typedef VectorParameter<bool>
Definition at line 822 of file Parameter.h.
DoubleParameter
using marlinmt::DoubleParameter = typedef Parameter<double>
Definition at line 815 of file Parameter.h.
DoubleVectorParameter
using marlinmt::DoubleVectorParameter = typedef VectorParameter<double>
Definition at line 821 of file Parameter.h.
FloatParameter
using marlinmt::FloatParameter = typedef Parameter<float>
Definition at line 814 of file Parameter.h.
FloatVectorParameter
using marlinmt::FloatVectorParameter = typedef VectorParameter<float>
Definition at line 820 of file Parameter.h.
H1DEntry
using marlinmt::H1DEntry = typedef book::Handle<book::Entry<Hist1D> >
Definition at line 49 of file MarlinMTBookConfig.h.
H1DHandle
using marlinmt::H1DHandle = typedef book::Handle<Hist1D>
Definition at line 61 of file MarlinMTBookConfig.h.
H1FEntry
using marlinmt::H1FEntry = typedef book::Handle<book::Entry<Hist1F> >
Definition at line 48 of file MarlinMTBookConfig.h.
H1FHandle
using marlinmt::H1FHandle = typedef book::Handle<Hist1F>
Definition at line 60 of file MarlinMTBookConfig.h.
H1IEntry
using marlinmt::H1IEntry = typedef book::Handle<book::Entry<Hist1I> >
Definition at line 50 of file MarlinMTBookConfig.h.
H1IHandle
using marlinmt::H1IHandle = typedef book::Handle<Hist1I>
Definition at line 62 of file MarlinMTBookConfig.h.
H2DEntry
using marlinmt::H2DEntry = typedef book::Handle<book::Entry<Hist2D> >
Definition at line 52 of file MarlinMTBookConfig.h.
H2DHandle
using marlinmt::H2DHandle = typedef book::Handle<Hist2D>
Definition at line 64 of file MarlinMTBookConfig.h.
H2FEntry
using marlinmt::H2FEntry = typedef book::Handle<book::Entry<Hist2F> >
Definition at line 51 of file MarlinMTBookConfig.h.
H2FHandle
using marlinmt::H2FHandle = typedef book::Handle<Hist2F>
Definition at line 63 of file MarlinMTBookConfig.h.
H2IEntry
using marlinmt::H2IEntry = typedef book::Handle<book::Entry<Hist2I> >
Definition at line 53 of file MarlinMTBookConfig.h.
H2IHandle
using marlinmt::H2IHandle = typedef book::Handle<Hist2I>
Definition at line 65 of file MarlinMTBookConfig.h.
H3DEntry
using marlinmt::H3DEntry = typedef book::Handle<book::Entry<Hist3D> >
Definition at line 55 of file MarlinMTBookConfig.h.
H3DHandle
using marlinmt::H3DHandle = typedef book::Handle<Hist3D>
Definition at line 67 of file MarlinMTBookConfig.h.
H3FEntry
using marlinmt::H3FEntry = typedef book::Handle<book::Entry<Hist3F> >
Definition at line 54 of file MarlinMTBookConfig.h.
H3FHandle
using marlinmt::H3FHandle = typedef book::Handle<Hist3F>
Definition at line 66 of file MarlinMTBookConfig.h.
H3IEntry
using marlinmt::H3IEntry = typedef book::Handle<book::Entry<Hist3I> >
Definition at line 56 of file MarlinMTBookConfig.h.
H3IHandle
using marlinmt::H3IHandle = typedef book::Handle<Hist3I>
Definition at line 68 of file MarlinMTBookConfig.h.
Hist1D
using marlinmt::Hist1D = typedef book::types::H1D
Definition at line 36 of file MarlinMTBookConfig.h.
Hist1F
using marlinmt::Hist1F = typedef book::types::H1F
Definition at line 35 of file MarlinMTBookConfig.h.
Hist1I
using marlinmt::Hist1I = typedef book::types::H1I
Definition at line 37 of file MarlinMTBookConfig.h.
Hist2D
using marlinmt::Hist2D = typedef book::types::H2D
Definition at line 39 of file MarlinMTBookConfig.h.
Hist2F
using marlinmt::Hist2F = typedef book::types::H2F
Definition at line 38 of file MarlinMTBookConfig.h.
Hist2I
using marlinmt::Hist2I = typedef book::types::H2I
Definition at line 40 of file MarlinMTBookConfig.h.
Hist3D
using marlinmt::Hist3D = typedef book::types::H3D
Definition at line 42 of file MarlinMTBookConfig.h.
Hist3F
using marlinmt::Hist3F = typedef book::types::H3F
Definition at line 41 of file MarlinMTBookConfig.h.
Hist3I
using marlinmt::Hist3I = typedef book::types::H3I
Definition at line 43 of file MarlinMTBookConfig.h.
HistConfig
template<typename P , typename W , std::size_t D> using marlinmt::HistConfig = typedef book::types::HistConfig<P, W, D>
Definition at line 18 of file MarlinMTBookConfig.h.
HistT
template<typename P , typename W , std::size_t D> using marlinmt::HistT = typedef book::types::HistT<HistConfig<P, W, D> >
Definition at line 21 of file MarlinMTBookConfig.h.
IntParameter
using marlinmt::IntParameter = typedef Parameter<int>
Definition at line 812 of file Parameter.h.
IntVectorParameter
using marlinmt::IntVectorParameter = typedef VectorParameter<int>
Definition at line 818 of file Parameter.h.
StringParameter
using marlinmt::StringParameter = typedef Parameter<std::string>
Definition at line 817 of file Parameter.h.
StringVectorParameter
using marlinmt::StringVectorParameter = typedef VectorParameter<std::string>
Definition at line 823 of file Parameter.h.
UIntParameter
using marlinmt::UIntParameter = typedef Parameter<unsigned int>
Definition at line 813 of file Parameter.h.
UIntVectorParameter
using marlinmt::UIntVectorParameter = typedef VectorParameter<unsigned int>
Definition at line 819 of file Parameter.h.
ValidatorFunctionT
template<typename T > using marlinmt::ValidatorFunctionT = typedef std::function<bool(const T &)>
Definition at line 12 of file Validator.h.
Enumeration Type Documentation
EParameterType
enum marlinmt::EParameterType strong
EParameterType enumerator Enumerates parameter types supported by Marlin.
Enumerator
eSimple
eVector
Simple (scalar) parameter.
Vector parameter
Definition at line 27 of file Parameter.h.
Function Documentation
constructPath()
std::filesystem::path marlinmt::constructPath (const Processor * proc, const std::filesystem::path & path)
construct absolute path from relative path and processor.
Parameters
proc Processor who owned the path
path absolute path in processor
Definition at line 17 of file ProcessorApi.cc.
References marlinmt::Component::name().
Referenced by marlinmt::ProcessorApi::Book::bookHist1D(), marlinmt::ProcessorApi::Book::bookHist1F(), marlinmt::ProcessorApi::Book::bookHist1I(), marlinmt::ProcessorApi::Book::bookHist2D(), marlinmt::ProcessorApi::Book::bookHist2F(), marlinmt::ProcessorApi::Book::bookHist2I(), marlinmt::ProcessorApi::Book::bookHist3D(), marlinmt::ProcessorApi::Book::bookHist3F(), marlinmt::ProcessorApi::Book::bookHist3I(), marlinmt::ProcessorApi::Book::getHist1D(), marlinmt::ProcessorApi::Book::getHist1F(), marlinmt::ProcessorApi::Book::getHist1I(), marlinmt::ProcessorApi::Book::getHist2D(), marlinmt::ProcessorApi::Book::getHist2F(), marlinmt::ProcessorApi::Book::getHist2I(), marlinmt::ProcessorApi::Book::getHist3D(), marlinmt::ProcessorApi::Book::getHist3F(), and marlinmt::ProcessorApi::Book::getHist3I().
getObject()
template<typename HistT > book::Handle<book::Entry<HistT> > marlinmt::getObject (const BookStoreManager & storeManager, const std::filesystem::path & path, const std::string_view & name)
Definition at line 27 of file ProcessorApi.cc.
References marlinmt::BookStoreManager::getKey(), and marlinmt::BookStoreManager::getObject().
INSTANCIATIONS_HIST() [1/9]
marlinmt::INSTANCIATIONS_HIST (Hist1F)
INSTANCIATIONS_HIST() [2/9]
marlinmt::INSTANCIATIONS_HIST (Hist1D)
INSTANCIATIONS_HIST() [3/9]
marlinmt::INSTANCIATIONS_HIST (Hist1I)
INSTANCIATIONS_HIST() [4/9]
marlinmt::INSTANCIATIONS_HIST (Hist2F)
INSTANCIATIONS_HIST() [5/9]
marlinmt::INSTANCIATIONS_HIST (Hist2D)
INSTANCIATIONS_HIST() [6/9]
marlinmt::INSTANCIATIONS_HIST (Hist2I)
INSTANCIATIONS_HIST() [7/9]
marlinmt::INSTANCIATIONS_HIST (Hist3F)
INSTANCIATIONS_HIST() [8/9]
marlinmt::INSTANCIATIONS_HIST (Hist3D)
INSTANCIATIONS_HIST() [9/9]
marlinmt::INSTANCIATIONS_HIST (Hist3I)
MARLINMT_DEFINE_EXCEPTION() [1/4]
marlinmt::MARLINMT_DEFINE_EXCEPTION (SkipEventException)
Definition of Marlin exceptions.
Referenced by marlinmt::Exception::Exception().
MARLINMT_DEFINE_EXCEPTION() [2/4]
marlinmt::MARLINMT_DEFINE_EXCEPTION (StopProcessingException)
MARLINMT_DEFINE_EXCEPTION() [3/4]
marlinmt::MARLINMT_DEFINE_EXCEPTION (ParseException)
MARLINMT_DEFINE_EXCEPTION() [4/4]
marlinmt::MARLINMT_DEFINE_EXCEPTION (BookStoreException)
operator!=()
template<typename T , typename S > bool marlinmt::operator!= (const Parameter< T > & lhs, const S & rhs) inline
Definition at line 777 of file Parameter.h.
References marlinmt::ParameterBase< T >::get().
operator<()
template<typename T , typename S > bool marlinmt::operator< (const Parameter< T > & lhs, const S & rhs) inline
Definition at line 784 of file Parameter.h.
operator<<() [1/3]
std::ostream & marlinmt::operator<< (std::ostream & s, Expression & e)
Definition at line 12 of file LogicalExpressions.cc.
References marlinmt::Expression::AND, marlinmt::Expression::isNot, marlinmt::Expression::Operation, and marlinmt::Expression::Value.
operator<<() [2/3]
std::ostream & marlinmt::operator<< (std::ostream & stream, const Configuration & cfg)
Stream operator.
Definition at line 196 of file Configuration.cc.
References marlinmt::Configuration::constants(), printSection(), marlinmt::Configuration::section(), and marlinmt::Configuration::sections().
operator<<() [3/3]
template<typename T > std::ostream& marlinmt::operator<< (std::ostream & stream, const Parameter< T > & rhs) inline
Definition at line 762 of file Parameter.h.
operator<=()
template<typename T , typename S > bool marlinmt::operator<= (const Parameter< T > & lhs, const S & rhs) inline
Definition at line 791 of file Parameter.h.
operator==()
template<typename T , typename S > bool marlinmt::operator== (const Parameter< T > & lhs, const S & rhs) inline
Definition at line 770 of file Parameter.h.
References marlinmt::ParameterBase< T >::get().
operator>()
template<typename T , typename S > bool marlinmt::operator> (const Parameter< T > & lhs, const S & rhs) inline
Definition at line 798 of file Parameter.h.
References marlinmt::ParameterBase< T >::get().
operator>=()
template<typename T , typename S > bool marlinmt::operator>= (const Parameter< T > & lhs, const S & rhs) inline
Definition at line 805 of file Parameter.h.
References marlinmt::ParameterBase< T >::get().
printSection()
void marlinmt::printSection (const ConfigSection & section, std::ostream & stream, const std::string & prefix)
Definition at line 183 of file Configuration.cc.
References marlinmt::ConfigSection::name(), marlinmt::ConfigSection::parameter(), marlinmt::ConfigSection::parameterNames(), marlinmt::ConfigSection::section(), and marlinmt::ConfigSection::subsectionNames().
Referenced by operator<<().