MarlinMT: marlinmt::book::Flags Namespace Reference
marlinmt::book::Flags Namespace Reference
Flags for different purposes in marlinmt::book.
Namespaces
Book
flags for booking
Functions
constexpr unsigned long long value (const Flag_t &flag)
Detailed Description
Flags for different purposes in marlinmt::book.
Function Documentation
value()
constexpr unsigned long long marlinmt::book::Flags::value (const Flag_t & flag)
Definition at line 106 of file Flags.h.
References marlinmt::book::Flag_t::_initValue.
Referenced by marlinmt::Configurable::addParameter(), marlinmt::validator::combineAnd(), marlinmt::validator::combineOr(), marlinmt::validator::constraints(), marlinmt::ParameterImpl::construct(), marlinmt::Processor::end(), marlinmt::book::EntryDataBase< types::HistT< Config > >::EntryDataBase(), marlinmt::validator::expectSize(), marlinmt::validator::forEach(), marlinmt::Component::getParameters(), marlinmt::validator::greater(), marlinmt::validator::greaterEqual(), marlinmt::book::EntryMultiShared< types::HistT< Config > >::handle(), marlinmt::validator::inRange(), marlinmt::validator::less(), marlinmt::validator::lessEqual(), marlinmt::book::EntryDataBase< types::HistT< Config > >::multiCopy(), marlinmt::book::EntryDataBase< types::HistT< Config > >::multiShared(), marlinmt::book::details::Entry::EntryHelper::Conclusion< T, TF >::needs(), marlinmt::validator::notEmpty(), marlinmt::validator::notInfinity(), marlinmt::ParameterImpl::ParameterImpl(), marlinmt::XMLConfigReader::parseConstant(), marlinmt::LCIOOutputProcessor::processRunHeader(), marlinmt::ProcessorConditionsExtension::set(), marlinmt::ParameterBase< bool >::set(), marlinmt::Processor::setRuntimeOption(), marlinmt::book::EntryDataBase< types::HistT< Config > >::single(), marlinmt::validator::sizeModulo(), marlinmt::StringUtil::split(), and marlinmt::details::convert< std::string >::to_string().