MarlinMT: marlinmt::book::Flags::Book Namespace Reference
marlinmt::book::Flags::Book Namespace Reference
flags for booking
Functions
constexpr Flag_t Default (0)
use default arguments
constexpr Flag_t Single (1U<< 0U)
vanilla object.
constexpr Flag_t MultiShared (1U<< 1U)
create one instance witch concurrent access.
constexpr Flag_t MultiCopy (1U<< 2U)
create multiple instances of booked object (if possible) to avoid sync points
constexpr Flag_t Store (1U<< 3U)
store object in file at end of lifetime
Detailed Description
flags for booking
Function Documentation
Default()
constexpr Flag_t marlinmt::book::Flags::Book::Default (0)
use default arguments
Referenced by marlinmt::BookStoreManager::bookHist().
MultiCopy()
constexpr Flag_t marlinmt::book::Flags::Book::MultiCopy (1U<< 2U)
create multiple instances of booked object (if possible) to avoid sync points
Referenced by marlinmt::BookStoreManager::bookHist(), marlinmt::book::BookStore::bookMultiCopy(), marlinmt::book::EntryMultiShared< types::HistT< Config > >::handle(), marlinmt::BookStoreManager::initialize(), marlinmt::book::EntryDataBase< types::HistT< Config > >::multiCopy(), and marlinmt::book::EntryDataBase< types::HistT< Config > >::single().
MultiShared()
constexpr Flag_t marlinmt::book::Flags::Book::MultiShared (1U<< 1U)
create one instance witch concurrent access.
Referenced by marlinmt::BookStoreManager::bookHist(), marlinmt::book::BookStore::bookMultiShared(), marlinmt::book::EntryMultiShared< types::HistT< Config > >::handle(), marlinmt::BookStoreManager::initialize(), marlinmt::book::EntryDataBase< types::HistT< Config > >::multiCopy(), and marlinmt::book::EntryDataBase< types::HistT< Config > >::multiShared().
Single()
constexpr Flag_t marlinmt::book::Flags::Book::Single (1U<< 0U)
vanilla object.
Referenced by marlinmt::BookStoreManager::bookHist(), marlinmt::book::BookStore::bookSingle(), marlinmt::book::EntryDataBase< types::HistT< Config > >::EntryDataBase(), marlinmt::book::EntryMultiShared< types::HistT< Config > >::handle(), marlinmt::BookStoreManager::initialize(), and marlinmt::book::EntryDataBase< types::HistT< Config > >::single().
Store()
constexpr Flag_t marlinmt::book::Flags::Book::Store (1U<< 3U)
store object in file at end of lifetime
Referenced by marlinmt::BookStoreManager::bookHist(), and marlinmt::BookStoreManager::initialize().