MarlinMT: marlinmt::book::EntryKey Struct Reference
marlinmt::book::EntryKey Struct Reference
Data selection to identify and manage an Entry.
#include <EntryData.h>
Public Member Functions
EntryKey ()=default
default constructor.
EntryKey (const std::type_index &t)
Construct typed EntryKey.
Public Attributes
std::filesystem::path path {""}
virtual Entry path
std::size_t mInstances {0}
number of memory instances
std::type_index type {typeid(void)}
Type of object stored in Entry.
Flag_t flags {}
Status flags from Entry.
std::size_t idx {std::numeric_limits<std::size_t>::max()}
unique number for Entry
Detailed Description
Data selection to identify and manage an Entry.
Definition at line 21 of file EntryData.h.
Constructor & Destructor Documentation
EntryKey() [1/2]
marlinmt::book::EntryKey::EntryKey () default
default constructor.
EntryKey() [2/2]
marlinmt::book::EntryKey::EntryKey (const std::type_index & t) inline explicit
Construct typed EntryKey.
Definition at line 27 of file EntryData.h.
Member Data Documentation
flags
Flag_t marlinmt::book::EntryKey::flags {}
Status flags from Entry.
Definition at line 36 of file EntryData.h.
Referenced by marlinmt::book::details::Entry::EntryHelper::handle().
idx
std::size_t marlinmt::book::EntryKey::idx {std::numeric_limits<std::size_t>::max()}
unique number for Entry
Definition at line 38 of file EntryData.h.
Referenced by marlinmt::book::BookStore::addEntry(), marlinmt::book::BookStore::getPtr(), and std::less< marlinmt::book::EntryKey >::operator()().
mInstances
std::size_t marlinmt::book::EntryKey::mInstances {0}
number of memory instances
Definition at line 32 of file EntryData.h.
Referenced by marlinmt::book::details::Entry::EntryHelper::ThrowIfOutOfBound().
path
std::filesystem::path marlinmt::book::EntryKey::path {""}
virtual Entry path
Definition at line 30 of file EntryData.h.
Referenced by marlinmt::book::BookStore::addEntry(), marlinmt::book::BookStore::bookMultiCopy(), marlinmt::book::BookStore::bookMultiShared(), marlinmt::book::BookStore::bookSingle(), and marlinmt::book::StoreWriter::writeSelection().
type
std::type_index marlinmt::book::EntryKey::type {typeid(void)}
Type of object stored in Entry.
Definition at line 34 of file EntryData.h.
Referenced by marlinmt::BookStoreManager::getObject(), and marlinmt::book::StoreWriter::writeSelection().
The documentation for this struct was generated from the following file:
EntryData.h